force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Group__c/fields/Codes__c.field-meta.xml
<CustomField>
    <fullName>Codes__c</fullName>
    <description>acriss codes that are part of this group</description>
    <inlineHelpText>acriss codes that are part of this group</inlineHelpText>
    <label>Codes</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Acriss_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Acriss_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>CAZZ</fullName>
    </customValue>
    <customValue>
        <fullName>CDAE</fullName>
    </customValue>
    <customValue>
        <fullName>CDAH</fullName>
    </customValue>
    <customValue>
        <fullName>CDAR</fullName>
    </customValue>
    <customValue>
        <fullName>CDMR</fullName>
    </customValue>
    <customValue>
        <fullName>CFMR</fullName>
    </customValue>
    <customValue>
        <fullName>CLAE</fullName>
    </customValue>
    <customValue>
        <fullName>CLAH</fullName>
    </customValue>
    <customValue>
        <fullName>CLAR</fullName>
    </customValue>
    <customValue>
        <fullName>CWAH</fullName>
    </customValue>
    <customValue>
        <fullName>CWAR</fullName>
    </customValue>
    <customValue>
        <fullName>CWMR</fullName>
    </customValue>
    <customValue>
        <fullName>ECAE</fullName>
    </customValue>
    <customValue>
        <fullName>ECMR</fullName>
    </customValue>
    <customValue>
        <fullName>ETMR</fullName>
    </customValue>
    <customValue>
        <fullName>FDAR</fullName>
    </customValue>
    <customValue>
        <fullName>FFAR</fullName>
    </customValue>
    <customValue>
        <fullName>FVAR</fullName>
    </customValue>
    <customValue>
        <fullName>FWAH</fullName>
    </customValue>
    <customValue>
        <fullName>FWAR</fullName>
    </customValue>
    <customValue>
        <fullName>IDAE</fullName>
    </customValue>
    <customValue>
        <fullName>IDAR</fullName>
    </customValue>
    <customValue>
        <fullName>IFAH</fullName>
    </customValue>
    <customValue>
        <fullName>IFAR</fullName>
    </customValue>
    <customValue>
        <fullName>IFMR</fullName>
    </customValue>
    <customValue>
        <fullName>ILAE</fullName>
    </customValue>
    <customValue>
        <fullName>ILAH</fullName>
    </customValue>
    <description>Acriss Codes used in SIXT DK</description>
    <masterLabel>Acriss Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VehicleGroupUtility.cls
/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * Utility class for Vehicle Group object.
 *
 * It provides following functionality:
 * - mapping from Acriss code to Vehicle_Group__c
 *
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Marek Smerak      <marek.smerak@wipro.com>
 * @modifiedBy     Marek Smerak      <marek.smerak@wipro.com>
 * @version        1.0
 * @created        2022-01-01
 * @modified       2022-04-01
 * @systemLayer    Utility
 * @see            SIX-4
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v1.0            marek.smerak@wipro.com
 * 2022-04-01      initial version
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
 */
public inherited sharing class VehicleGroupUtility {
    // mapping from acriss code to vehicle group
    private static Map<String, Vehicle_Group__c> mAcriss2VehicleGroup;

    public static Map<String, Vehicle_Group__c> getAcriss2VehicleGroupMap() {
        if (mAcriss2VehicleGroup == null) {
            mAcriss2VehicleGroup = new Map<String, Vehicle_Group__c>();
            for (Vehicle_Group__c vehicleGroup : [SELECT Id, Codes__c FROM Vehicle_Group__c]) {
                System.debug(LoggingLevel.FINE, 'creating mapping for Vehicle Group: ' + vehicleGroup);
                List<String> codes = vehicleGroup.Codes__c.split(';');
                for (String singleAcrissCode : codes) {
                    mAcriss2VehicleGroup.put(singleAcrissCode, vehicleGroup);
                }
            }
        }
        System.debug(LoggingLevel.FINE, 'Vehicle Group map: ' + mAcriss2VehicleGroup);
        return mAcriss2VehicleGroup;
    }
}