force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/ACRISS_Code__c.field-meta.xml
<CustomField>
    <fullName>ACRISS_Code__c</fullName>
    <label>ACRISS Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Airbags__c.field-meta.xml
<CustomField>
    <fullName>Airbags__c</fullName>
    <description>Airbags, antal</description>
    <label>Airbags</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/AutoDesktop_Id__c.field-meta.xml
<CustomField>
    <fullName>AutoDesktop_Id__c</fullName>
    <description>vehicle ID in AutoDesktop</description>
    <inlineHelpText>vehicle ID in AutoDesktop</inlineHelpText>
    <label>AutoDesktop Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Automatic_gears__c.field-meta.xml
<CustomField>
    <fullName>Automatic_gears__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Autogear</description>
    <label>Automatic gears</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Battery_Capacity_kWh__c.field-meta.xml
<CustomField>
    <fullName>Battery_Capacity_kWh__c</fullName>
    <label>Battery Capacity (kWh)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Bluetooth__c.field-meta.xml
<CustomField>
    <fullName>Bluetooth__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bluetooth</description>
    <label>Bluetooth</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alfa Romeo</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Citroën</fullName>
            </value>
            <value>
                <fullName>Cupra</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Land Rover</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mercedes Benz</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Opel</fullName>
            </value>
            <value>
                <fullName>Peugeot</fullName>
            </value>
            <value>
                <fullName>Polestar</fullName>
            </value>
            <value>
                <fullName>Porsche</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
            <value>
                <fullName>Seat</fullName>
            </value>
            <value>
                <fullName>Skoda</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>Volvo</fullName>
            </value>
            <value>
                <fullName>VW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Buyer_Account__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Buyer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Car_remark__c.field-meta.xml
<CustomField>
    <fullName>Car_remark__c</fullName>
    <label>Car remark</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/CO2__c.field-meta.xml
<CustomField>
    <fullName>CO2__c</fullName>
    <label>CO2 (g/km)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <label>Color</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Current_KM__c.field-meta.xml
<CustomField>
    <fullName>Current_KM__c</fullName>
    <label>Current KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Delivery_cost__c.field-meta.xml
<CustomField>
    <fullName>Delivery_cost__c</fullName>
    <description>What is the delivery costs?</description>
    <inlineHelpText>What is the delivery costs?</inlineHelpText>
    <label>Delivery cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/First_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Registration_Date__c</fullName>
    <description>Date when the vehicle was first registered with Danish tax agency</description>
    <inlineHelpText>Date when the vehicle was first registered with Danish tax agency</inlineHelpText>
    <label>First Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Fuel_type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_type__c</fullName>
    <label>Fuel type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DI</fullName>
                <label>Diesel</label>
            </value>
            <value>
                <fullName>EL</fullName>
                <label>Electric</label>
            </value>
            <value>
                <fullName>HBBP</fullName>
                <label>Hybrid Petrol</label>
            </value>
            <value>
                <fullName>HBD</fullName>
                <label>Hybrid Diesel</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Petrol</label>
            </value>
            <value>
                <fullName>HBB</fullName>
                <label>Hybrid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/kmPrL__c.field-meta.xml
<CustomField>
    <fullName>kmPrL__c</fullName>
    <label>KM/L</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Vehicle_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Last_Vehicle_Inspection__c</fullName>
    <description>date of the last vehicle inspection</description>
    <inlineHelpText>date of the last vehicle inspection</inlineHelpText>
    <label>Last Vehicle Inspection</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_System__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_System__c</fullName>
    <description>License Plate / Registration Number in official format used with SKAT and with external communication or integration</description>
    <externalId>true</externalId>
    <inlineHelpText>License Plate / Registration Number in official format used with SKAT</inlineHelpText>
    <label>License Plate (System)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/licensePlateCost__c.field-meta.xml
<CustomField>
    <fullName>licensePlateCost__c</fullName>
    <label>License Plate Cost</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Link_to_Retail_Website__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Retail_Website__c</fullName>
    <description>ling to navigate to the vehicle on SIXT Retail Sales Website</description>
    <inlineHelpText>ling to navigate to the vehicle on SIXT Retail Sales Website</inlineHelpText>
    <label>Link to Retail Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>What model is the car?</description>
    <inlineHelpText>What model is the car?</inlineHelpText>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model_Name__c.field-meta.xml
<CustomField>
    <fullName>Model_Name__c</fullName>
    <description>model official name as defined in AutoDesktop (and DMR) catalogue</description>
    <inlineHelpText>model official name as defined in AutoDesktop (and DMR) catalogue</inlineHelpText>
    <label>Model Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Navigation__c.field-meta.xml
<CustomField>
    <fullName>Navigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Navi</description>
    <label>Navigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/NCAP__c.field-meta.xml
<CustomField>
    <fullName>NCAP__c</fullName>
    <label>NCAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Non_standard_Accessories__c.field-meta.xml
<CustomField>
    <fullName>Non_standard_Accessories__c</fullName>
    <description>Udstyr udover std.</description>
    <label>Non-standard Accessories</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Parking_sensor__c.field-meta.xml
<CustomField>
    <fullName>Parking_sensor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>P-Sensor</description>
    <label>Parking sensor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <description>how many km the e-car can drive
populated manually by Car Control</description>
    <inlineHelpText>how many km the e-car can drive</inlineHelpText>
    <label>Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Re_marketing_Status__c.field-meta.xml
<CustomField>
    <fullName>Re_marketing_Status__c</fullName>
    <label>Re-marketing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to sell</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Not sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Speed_Pilot__c.field-meta.xml
<CustomField>
    <fullName>Speed_Pilot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Speed Pilot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Batch__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Batch__c</fullName>
    <label>Vehicle Batch</label>
    <referenceTo>vehicleBatch__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/REST_XfleetVehicle.cls
@RestResource(urlMapping='/Xfleet/v1/Vehicle/*')
global with sharing class REST_XfleetVehicle {

    global static final String ERROR_NO_BUYER = 'Buyer cannot be found in Xfleet!';
    global static final String ERROR_NO_BATCH = 'Vehicle Batch cannot be found in Xfleet!';


    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        VehicleWrapper respBody;
        try {
            // need vehicle Id from URI
            String vehicleId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            Vehicle__c xfleetVehicle = queryVehicle(vehicleId);
            respBody = vehicle2Wrapper(xfleetVehicle);
            res.statusCode = 200;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'error in vehicle create processing: ' + ex.getMessage());
            System.debug(LoggingLevel.ERROR, 'cause: ' + ex.getCause());
            res.statusCode = 500;
            respBody = new VehicleWrapper();
            respBody.errorMessage = ex.getMessage();
        }
        res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    }

    @HttpPost
    global static void doPost(VehicleWrapper vehicle) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        VehicleResponseWrapper respBody = new VehicleResponseWrapper();
        try {
            System.debug(vehicle.range);
            System.debug(vehicle.firstRegistrationDate);
            Vehicle__c xfleetVehicle = wrapper2Vehicle(vehicle, null);
            // batch assignment;
            xfleetVehicle.Vehicle_Batch__c = getBatchId(vehicle.vehicleBatchName);
            // insert into Xfleet
            insert xfleetVehicle;
            respBody.id = xfleetVehicle.Id;
            res.statusCode = 201;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'error in vehicle create processing: ' + ex.getMessage());
            System.debug(LoggingLevel.ERROR, 'cause: ' + ex.getCause());
            res.statusCode = 500;
            respBody.errorMessage = ex.getMessage();
        }
        res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    }

    @HttpPatch
    global static void doPatch(VehicleWrapper vehicle) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        VehicleResponseWrapper respBody = new VehicleResponseWrapper();
        try {
            // need vehicle Id from URI
            String vehicleId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            Vehicle__c xfleetVehicle = wrapper2Vehicle(vehicle, Id.valueOf(vehicleId));
            System.debug(LoggingLevel.DEBUG, 'vehicle before update: ' + xfleetVehicle);
            update xfleetVehicle;
            respBody.id = xfleetVehicle.Id;
            res.statusCode = 200;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'error in vehicle create processing: ' + ex.getMessage());
            System.debug(LoggingLevel.ERROR, 'cause: ' + ex.getCause());
            res.statusCode = 500;
            respBody.errorMessage = ex.getMessage();
        }
        res.responseBody = Blob.valueOf(JSON.serialize(respBody, true));
    }

    private static Vehicle__c queryVehicle(Id vehicleId) {
        Vehicle__c vehicle = [
            SELECT
                ACRISS_Code__c,
                Airbags__c,
                Automatic_gears__c,
                Battery_Capacity_kWh__c,
                Bluetooth__c,
                Brand__c,
                Buyer_Account__r.Name,
                Car_remark__c,
                CO2__c,
                color__c,
                kmPrL__c,
                Speed_Pilot__c,
                Link_to_Retail_Website__c,
                Delivery_cost__c,
                Non_standard_Accessories__c,
                AutoDesktop_Id__c,
                First_Registration_Date__c,
                Fuel_type__c,
                Last_Vehicle_Inspection__c,
                licensePlateCost__c,
                Current_KM__c,
                Model_Name__c,
                Model__c,
                Model_Year__c,
                Navigation__c,
                NCAP__c,
                Parking_sensor__c,
                Range__c,
                License_Plate_System__c,
                Registration_Date__c,
                Re_marketing_Status__c,
                Retail_Price__c,
                Retail_Sales__c,
                Seatbeltalarms__c,
                Service_interval_Years_KM__c,
                Status__c,
                Sixt_steel_purchase_price__c,
                Tank_size_liters__c,
                Tire_type__c,
                Vehicle_Batch__r.Name,
                vinNumber__c
            FROM Vehicle__c
            WHERE Id = :vehicleId
        ];
        return vehicle;
    }

    private static Id getBatchId(String batchName) {
        Id batchId;
        // batch name not defined in the request, get default batch from setting
        if (String.isBlank(batchName)) {
            FleetManagementConfig__c config = FleetManagementConfig__c.getInstance();
            batchId = Id.valueOf(config.DefaultBatchId__c);
        } else {
            List<vehicleBatch__c> batches = [SELECT Id FROM vehicleBatch__c WHERE Name = :batchName LIMIT 1];
            if (batches.isEmpty()) {
                throw new XfleetVehicleException(ERROR_NO_BATCH);
            } 
            batchId = batches.get(0).Id;
        }
        return batchId;
    }

    private static VehicleWrapper vehicle2Wrapper(Vehicle__c vehicle) {
        VehicleWrapper wrapper = new VehicleWrapper();
        wrapper.acrissCode = vehicle.ACRISS_Code__c;
        wrapper.airbagsNumber = (Integer) vehicle.Airbags__c;
        wrapper.automaticGears = vehicle.Automatic_gears__c;
        wrapper.batteryCapacity = (Integer) vehicle.Battery_Capacity_kWh__c;
        wrapper.bluetooth = vehicle.Bluetooth__c;
        wrapper.brandName = vehicle.Brand__c;
        wrapper.buyerAccountName = vehicle.Buyer_Account__r?.Name;
        wrapper.carRemarks = vehicle.Car_remark__c;
        wrapper.co2Emissions = (Integer) vehicle.CO2__c;
        wrapper.colorName = vehicle.color__c;
        wrapper.consumptionKmPerLiter = (Decimal) vehicle.kmPrL__c;
        wrapper.cruiseControl = vehicle.Speed_Pilot__c;
        wrapper.deeplink = vehicle.Link_to_Retail_Website__c;
        wrapper.deliveryCostsRetailDKK = (Integer) vehicle.Delivery_cost__c;
        wrapper.equipmentList = vehicle.Non_standard_Accessories__c;
        wrapper.externalId = vehicle.AutoDesktop_Id__c;
        wrapper.firstRegistrationDate = vehicle.First_Registration_Date__c;
        wrapper.fuelType = vehicle.Fuel_type__c;
        wrapper.lastVehicleInspection = vehicle.Last_Vehicle_Inspection__c;
        wrapper.licensePlateCostsDKK = (Integer) vehicle.licensePlateCost__c;
        wrapper.mileage = (Integer) vehicle.Current_KM__c;
        wrapper.modelName = vehicle.Model_Name__c;
        wrapper.modelXfleet = vehicle.Model__c;
        wrapper.modelYear = (Integer) vehicle.Model_Year__c;
        wrapper.navigation = vehicle.Navigation__c;
        wrapper.ncap = vehicle.NCAP__c;
        wrapper.parkingSensor = vehicle.Parking_sensor__c;
        wrapper.range = (Integer) vehicle.Range__c;
        wrapper.regNo = vehicle.License_Plate_System__c;
        wrapper.registrationDate = vehicle.Registration_Date__c;
        wrapper.remarketingStatus = vehicle.Re_marketing_Status__c;
        wrapper.retailPriceDKK = (Integer) vehicle.Retail_Price__c;
        wrapper.retailSales = vehicle.Retail_Sales__c;
        wrapper.seatbeltAlarmsNumber = (Integer) vehicle.Seatbeltalarms__c;
        wrapper.serviceInterval = vehicle.Service_interval_Years_KM__c;
        wrapper.status = vehicle.Status__c;
        wrapper.steelPriceDKK = (Integer) vehicle.Sixt_steel_purchase_price__c;
        wrapper.tankSize = (Integer) vehicle.Tank_size_liters__c;
        wrapper.tireType = vehicle.Tire_type__c;
        wrapper.vehicleBatchName = vehicle.Vehicle_Batch__r.Name;
        wrapper.vin = vehicle.vinNumber__c;
        return wrapper;
    }

    private static Vehicle__c wrapper2Vehicle(VehicleWrapper wrapper, Id vehicleId) {
        Vehicle__c vehicle;
        if (vehicleId == null) {
            vehicle = new Vehicle__c();
        } else {
            vehicle = new Vehicle__c(Id = vehicleId);
        }
        // set parameters from wrapper
        vehicle.ACRISS_Code__c = wrapper.acrissCode;
        vehicle.Airbags__c = wrapper.airbagsNumber;
        vehicle.Automatic_gears__c = wrapper.automaticGears;
        vehicle.Battery_Capacity_kWh__c = wrapper.batteryCapacity;
        vehicle.Bluetooth__c = wrapper.bluetooth;
        vehicle.Brand__c = wrapper.brandName;
        vehicle.Car_remark__c = wrapper.carRemarks;
        vehicle.CO2__c = wrapper.co2Emissions;
        vehicle.color__c = wrapper.colorName;
        vehicle.kmPrL__c = wrapper.consumptionKmPerLiter;
        vehicle.Speed_Pilot__c = wrapper.cruiseControl;
        vehicle.Link_to_Retail_Website__c = wrapper.deeplink;
        vehicle.Delivery_cost__c = wrapper.deliveryCostsRetailDKK;
        vehicle.Non_standard_Accessories__c = wrapper.equipmentList;
        vehicle.AutoDesktop_Id__c = wrapper.externalId;
        vehicle.First_Registration_Date__c = wrapper.firstRegistrationDate;
        vehicle.Fuel_type__c = wrapper.fuelType;
        vehicle.Last_Vehicle_Inspection__c = wrapper.lastVehicleInspection;
        vehicle.licensePlateCost__c = wrapper.licensePlateCostsDKK;
        vehicle.Current_KM__c = wrapper.mileage;
        vehicle.Model_Name__c = wrapper.modelName;
        vehicle.Model__c = wrapper.modelXfleet;
        vehicle.Model_Year__c = wrapper.modelYear;
        vehicle.Navigation__c = wrapper.navigation;
        vehicle.NCAP__c = wrapper.ncap;
        vehicle.Parking_sensor__c = wrapper.parkingSensor;
        vehicle.Range__c = wrapper.range;
        vehicle.License_Plate_System__c = wrapper.regNo;
        vehicle.Registration_Date__c = wrapper.registrationDate;
        vehicle.Re_marketing_Status__c = wrapper.remarketingStatus;
        vehicle.Retail_Price__c = wrapper.retailPriceDKK;
        vehicle.Retail_Sales__c = wrapper.retailSales;
        vehicle.Seatbeltalarms__c = wrapper.seatbeltAlarmsNumber;
        vehicle.Service_interval_Years_KM__c = wrapper.serviceInterval;
        vehicle.Status__c = wrapper.status;
        vehicle.Sixt_steel_purchase_price__c = wrapper.steelPriceDKK;
        vehicle.Tank_size_liters__c = wrapper.tankSize;
        vehicle.Tire_type__c = wrapper.tireType;
        vehicle.vinNumber__c = wrapper.vin;
        // buyer account defined?
        if (String.isNotBlank(wrapper.buyerAccountName)) {
            List<Account> buyerAccounts = [SELECT Name FROM Account WHERE Name = :wrapper.buyerAccountName LIMIT 1];
            if (buyerAccounts.isEmpty()) {
                throw new XfleetVehicleException(ERROR_NO_BUYER);
            }
            vehicle.Buyer_Account__c = buyerAccounts.get(0).Id;
        }
        // remove null values
        Map<String, Object> allFields = new Map<String, Object>(vehicle.getPopulatedFieldsAsMap());
        Map<String, Object> notNullFields = new Map<String, Object>();
        for (String fieldName : allFields.keySet()) {
            if (allFields.get(fieldName) != null) {
                notNullFields.put(fieldName, allFields.get(fieldName));
            }
        }
        System.debug(LoggingLevel.DEBUG, 'wrapper converted to vehicle, not null values: ' + notNullFields);
        return (Vehicle__c) JSON.deserialize(JSON.serialize(notNullFields), Vehicle__c.class);
    }

    global class VehicleWrapper {
        public String acrissCode;
        public Integer airbagsNumber;
        public Boolean automaticGears;
        public Integer batteryCapacity;
        public Boolean bluetooth;
        public String brandName;
        public String buyerAccountName;
        public String carRemarks;
        public Integer co2Emissions;
        public String colorName;
        public Decimal consumptionKmPerLiter;
        public Boolean cruiseControl;
        public String deeplink;
        public Integer deliveryCostsRetailDKK;
        public String equipmentList;
        public String externalId;
        public Date firstRegistrationDate;
        public String fuelType;
        public Date lastVehicleInspection;
        public Integer licensePlateCostsDKK;
        public Integer mileage;
        public String modelName;
        public String modelXfleet;
        public Integer modelYear;
        public Boolean navigation;
        public String ncap;
        public Boolean parkingSensor;
        public Integer range;
        public String regNo;
        public Date registrationDate;
        public String remarketingStatus;
        public Integer retailPriceDKK;
        public Boolean retailSales;
        public Integer seatbeltAlarmsNumber;
        public String serviceInterval;
        public String status;
        public Integer steelPriceDKK;
        public Integer tankSize;
        public String tireOwnership;
        public String tireSize;
        public String tireType;
        public String vehicleBatchName;
        public String vin;
        // add error message
        public String errorMessage;
    }

    global class VehicleResponseWrapper {
        public String id;
        public String errorMessage;
    }

    global class XfleetVehicleException extends Exception {}
}