force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Confirmed_Remarketing_Price_Converted__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Remarketing_Price_Converted__c</fullName>
    <description>system field to have remarketing price always in DKK and same type, so we can compare and sum vehicles</description>
    <formula>/* 1st use just regular Confirmed Remarketing Price (DKK) if exists */
BLANKVALUE(Confirmed_Remarketing_Price_DKK__c, 
		/* else use Confirmed Remarketing Price Full Tax if exists */
  BLANKVALUE(Confirmed_Remarketing_Price_Full_Tax_DKK__c,
		/* else use Confirmed Remarketing Price (EUR) and convert to DKK */				
		Confirmed_Remarketing_Price_EUR__c / $Setup.ConversionRate__c.DKK_to_EUR__c)
)</formula>
    <inlineHelpText>system field to have remarketing price always in DKK and same type, so we can compare and sum vehicles</inlineHelpText>
    <label>Confirmed Remarketing Price (Converted)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AutoITVehicleMarkAsSold.cls
public with sharing class AutoITVehicleMarkAsSold extends AutoITVehicle {

    public static final String METHOD_SUFFIX = '/MarkAsSold';

    public static final String TYPE_OF_SALE_DEFAULT = 'Wholesale';
    public static final String BUYER_TYPE_DEFAULT = 'Company';


    public AutoITVehicleMarkAsSold(String autoDesktopId) {
        super(autoDesktopId + METHOD_SUFFIX);
    }

    public override HttpRequest prepareRequest(Object params) {     
        String reqBody;
        if (params instanceOf String) {
            reqBody = JSON.serialize(JSON.deserializeUntyped( (String) params));
        } else {
            Vehicle__c car = (Vehicle__c) params;
            MarkAsSoldRequest reqBodyData = new MarkAsSoldRequest(car);
            reqBody = JSON.serialize(reqBodyData, true);
        }
        HttpRequest req = new HttpRequest();
        req.setMethod('PUT');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(reqBody);
        return req;
    }

    public class MarkAsSoldRequest {
        public Datetime dateOfSale { get; set; } 
        public Integer buyerAge { get; set; }
        public Integer salesPrice { get; set; }
        public String typeOfSale { get; set; }
        public String buyerType { get; set; }

        public MarkAsSoldRequest(Vehicle__c veh) {
            this.dateOfSale = System.now();
            this.typeOfSale = TYPE_OF_SALE_DEFAULT;
            this.buyerType = BUYER_TYPE_DEFAULT;
            this.salesPrice = Integer.valueOf(veh.Confirmed_Remarketing_Price_Converted__c);
        }
    }
}