force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/ACRISS_Code__c.field-meta.xml
<CustomField>
    <fullName>ACRISS_Code__c</fullName>
    <label>ACRISS Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>car group, automatically set from acriss code</description>
    <inlineHelpText>car group, automatically set from acriss code</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_status__c</fullName>
    <description>status of the vehicle in COBRA</description>
    <inlineHelpText>status of the vehicle in COBRA</inlineHelpText>
    <label>Vehicle status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - Car is rented</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Car is ready for rental</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 - Default</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 - Car is not ready, block for a reservation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 - Car is available, but not cleaned</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 - Car is not available, blocked for workshop etc.</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6 - Car is on workshop</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10 - Car arrived, but not checked in yet</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Car is checked in, but rental agreement not closed</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 - Car is blocked for sale</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 - Car is on station, but not on contract</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>99 - Car is on checkout</label>
            </value>
            <value>
                <fullName>00-</fullName>
                <label>00- - Car is defleeted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VehicleGroupUpdateBatchable.cls
/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * Batch Class to update Vehicle Group on Vehicles.
 * Already defleeted vehicles are excluded.
 *
 * It provides following functionality:
 * - mapping from Acriss code to Vehicle_Group__c
 *
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Marek Smerak      <marek.smerak@wipro.com>
 * @modifiedBy     Marek Smerak      <marek.smerak@wipro.com>
 * @version        1.0
 * @created        2022-04-01
 * @modified       2022-04-01
 * @systemLayer    Automatization
 * @see            SIX-4
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v1.0            marek.smerak@wipro.com
 * 2022-04-01      initial version
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
 */
global class VehicleGroupUpdateBatchable implements Database.Batchable<Vehicle__c> {
    
    private static Boolean runForecastUpdate = true;

    global List<Vehicle__c> start(Database.BatchableContext jobId) {
        List<Vehicle__c> recordList = new List<Vehicle__c>();
        recordList = [SELECT ACRISS_Code__c, Vehicle_Group__c FROM Vehicle__c WHERE ACRISS_Code__c != null AND Vehicle_status__c != '00-']; 
        return recordList;
    }

    global void execute(Database.BatchableContext jobId, List<Vehicle__c> recordList) {
        // get Acriss to Vehicle Group map
        Map<String, Vehicle_Group__c> mAcriss2VehicleGroup = VehicleGroupUtility.getAcriss2VehicleGroupMap();
        // list of vehicles to update
        List<Vehicle__c> vehiclesWithUpdatedGroup = new List<Vehicle__c>();
        // go through list of vehicles and set Vehicle group for each
        for (Vehicle__c vehicle : recordList) {
            Id vehicleGroupId;
            // map from acriss code
            if (String.isNotBlank(vehicle.ACRISS_Code__c)) {
                vehicleGroupId = mAcriss2VehicleGroup.get(vehicle.ACRISS_Code__c)?.Id;
            }
            // is vehicle group changed?
            if ((vehicleGroupId != null) && (vehicleGroupId != vehicle.Vehicle_Group__c)) {
                vehicle.Vehicle_Group__c = vehicleGroupId;
                vehiclesWithUpdatedGroup.add(vehicle);
            }
        }
        // any update?
        if (!vehiclesWithUpdatedGroup.isEmpty()) {
            update vehiclesWithUpdatedGroup;
        }
    }

    global void finish(Database.BatchableContext jobIdParam) {
        if (runForecastUpdate) {
            // one group at the time
            Id batchJobId = Database.executeBatch(new FleetForecastUpdateBatch(), 1);
        }
    }
}