force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alfa Romeo</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Citroën</fullName>
            </value>
            <value>
                <fullName>Cupra</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Land Rover</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mercedes Benz</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Opel</fullName>
            </value>
            <value>
                <fullName>Peugeot</fullName>
            </value>
            <value>
                <fullName>Polestar</fullName>
            </value>
            <value>
                <fullName>Porsche</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
            <value>
                <fullName>Seat</fullName>
            </value>
            <value>
                <fullName>Skoda</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>Volvo</fullName>
            </value>
            <value>
                <fullName>VW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Current_KM__c.field-meta.xml
<CustomField>
    <fullName>Current_KM__c</fullName>
    <label>Current KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_System__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_System__c</fullName>
    <description>License Plate / Registration Number in official format used with SKAT and with external communication or integration</description>
    <externalId>true</externalId>
    <inlineHelpText>License Plate / Registration Number in official format used with SKAT</inlineHelpText>
    <label>License Plate (System)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>What model is the car?</description>
    <inlineHelpText>What model is the car?</inlineHelpText>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AutoITVehicleObject.cls
/**
 * This class is wrapper object for Vehicle to be sent to AutoIT/AutoDesktop.
 *
 *
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Marek Smerak      <marek.smerak@wipro.com>
 * @modifiedBy     Marek Smerak      <marek.smerak@wipro.com>
 * @version        1.0
 * @created        2023-04-05
 * @modified       2023-04-05
 * @systemLayer    CallOuts
 * @see            SIXT-102, SIXT-103
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v1.0            marek.smerak@wipro.com
 * 2023-04-05      initial version
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
 */
public with sharing class AutoITVehicleObject {
    public String externalId { get; set; } // Salesforce record Id
    public String vin { get; set; }
    public String regNo { get; set; }
    public String dmrVehicleIdentifier { get; set; }
    public String dmrMakeModelVariantTypeId { get; set; }
    public String efTypeApprovalNumber { get; set; }
    public Integer tecDocKTypeNumber { get; set; }
    public Integer dkTypeApprovalCertificateNumber { get; set; }
    public Integer dkTypeApprovalVariantNumber { get; set; }
    public String dealerReferenceNumber { get; set; }
    public Integer firstRegistrationYear { get; set; }
    public Integer firstRegistrationMonth { get; set; }
    public Integer firstRegistrationDay { get; set; }
    public Integer modelYear { get; set; }
    public Integer vehicleInspectionYear { get; set; }
    public Integer vehicleInspectionMonth { get; set; }
    public Boolean vehicleInspectionPeriodicRequirement { get; set; }
    public Integer vehicleInspectionPeriodicIntervalMonths { get; set; }
    public Integer vehicleInspectionPeriodicBasisYear { get; set; }
    public Integer vehicleInspectionPeriodicBasisMonth { get; set; }
    public Integer newOrUsed { get; set; } // 1 or 2
    public Integer modelVariantId { get; set; }
    public Boolean trueToModelVariantRegister { get; set; }
    public Integer typeId { get; set; }
    public String typeName { get; set; }
    public Integer brandId { get; set; }
    public String brandName { get; set; }
    public String modelAdditionalDesignation { get; set; }
    public String modelSerieName { get; set; }
    public Integer modelId { get; set; }
    public String modelName { get; set; }
    public String bodyAdditionalDesignation { get; set; }
    public Integer bodyTypeId { get; set; }
    public String bodyTypeName { get; set; }
    public String bodyLengthTypeId { get; set; }
    public Integer doorCount { get; set; }
    public Integer seatCount { get; set; }
    public String transmissionAdditionalDesignation { get; set; }
    public Integer transmissionTypeId { get; set; }
    public String transmissionTypeName { get; set; }
    public Integer gearCount { get; set; }
    public String drivingWheelId { get; set; }
    public String engineAdditionalDesignation { get; set; }
    public String fuelTypeId { get; set; }
    public String engineSizeLitresDesignation { get; set; }
    public Integer maximumEffectHP { get; set; }
    public String additionalVariantDesignation { get; set; }
    public String equipmentLevelDesignation { get; set; }
    public String makeModelVariant { get; set; }
    public Integer colorId { get; set; }
    public String colorName { get; set; }
    public String colorOwnDescription { get; set; }
    public Integer mileage { get; set; }
    public String equipmentlist { get; set; }
    public String description { get; set; }
    public Boolean exVat { get; set; }
    public Decimal priceRetailDKK { get; set; }
    public Decimal priceRetailVatDKK { get; set; }
    public Decimal deliveryCostsRetailDKK { get; set; }
    public Decimal numberplateCostsDKK { get; set; }
    public Decimal priceWholesaleDKK { get; set; }
    public Decimal priceLowestAuctionDKK { get; set; }
    public Boolean absoluteDivestitureAuction	 { get; set; }
    public String deeplink { get; set; }
    public Boolean showOnSalesList { get; set; }
    public Boolean showOnAftermarketList { get; set; }
    public Integer currentResponsibleUserId { get; set; }
    public String edbNumber { get; set; }
    public Boolean isTradeInVehicle { get; set; }
    public String importerCode { get; set; }
    public Decimal salesPrice { get; set; }
    public Decimal priceRetailExRegistrationTax { get; set; }
    public Boolean priceRetailWithoutRegistrationTax { get; set; }
    public String comments { get; set; }
    public Datetime inventoryDate { get; set; }
    public Datetime lastVehicleInspection { get; set; }
    public Integer vinYear { get; set; }
    public Decimal expectedRegistrationTax { get; set; }
    public String commissionNumber { get; set; }
    // public Boolean import { get; set; } // we cannot send "import" as it is reserved word in Apex
    public Decimal repurchasePrice { get; set; }
    // TODO public CreateVehicleExtendedRequestType createVehicleExtendedRequest { get; set; }
    // TODO define inner class

    // Convert Xfleet Vehicle__c to API Vehicle object
    public AutoITVehicleObject(Vehicle__c vehicle) {
        this.vin = vehicle.vinNumber__c;
        this.regNo = vehicle.License_Plate_System__c;
        this.brandName = vehicle.Brand__c;
        this.modelName = vehicle.Model__c;
        this.mileage = (Integer)vehicle.Current_KM__c;
        // registration date
        this.firstRegistrationYear = vehicle.Registration_Date__c?.year();
        this.firstRegistrationMonth = vehicle.Registration_Date__c?.month();
        this.firstRegistrationDay = vehicle.Registration_Date__c?.day();
        // TODO complete the mapping
    }
}