force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/ACRISS_Code__c.field-meta.xml
<CustomField>
    <fullName>ACRISS_Code__c</fullName>
    <label>ACRISS Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>car group, automatically set from acriss code</description>
    <inlineHelpText>car group, automatically set from acriss code</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NO LONGER REQUIRED as batch can include several groups
we are buying vehicles for this Vehicle Group</description>
    <inlineHelpText>we are buying vehicles for this Vehicle Group</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Vehicle Batches</relationshipLabel>
    <relationshipName>Vehicle_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VehicleGroupUpdate_Test.cls
/* test class to test all classes related to VehicleGroupUpdate:
 * - VehicleGroupUtility
 * - VehicleGroupUpdateBatchable
 * - VehicleGroupUpdateScheduler
 */
@isTest
public with sharing class VehicleGroupUpdate_Test {
    @TestSetup
    static void makeData() {
        VehicleBatch__c testBatch = TestUtilitySIXT.createBatch();
        Map<String, Object> vehicleParams = new Map<String, Object>{ 'Acriss_code__c' => TestUtilitySIXT.ACCRIS_CODE };
        TestUtilitySIXT.createVehicle(testBatch.Id, vehicleParams);
    }

    // utility class test
    @isTest
    public static void calculateGroup() {
        Vehicle_Group__c testGroup = [SELECT Id FROM Vehicle_Group__c WHERE Name = :TestUtilitySIXT.VEHICLE_GROUP_NAME LIMIT 1];
        Map<String, Vehicle_Group__c> testMap = VehicleGroupUtility.getAcriss2VehicleGroupMap();
        System.assertEquals(testGroup.Id, testMap.get(TestUtilitySIXT.ACCRIS_CODE).Id, 'map from Acriss code to Vehicle Group is not correct');
    }

    // scheduler
    @isTest
    public static void vehicleGroupUpdateSchedulerTest() {
        String nextYear = String.valueOf(Date.today().year() + 1);
        Test.startTest();
        Id schedulerJobId = System.schedule('unitTestVehicleGroupUpdate', '0 0 0 1 1 ? ' + nextYear, new VehicleGroupUpdateScheduler());
        Test.stopTest();
    }

    // test of batch class and process
    @isTest
    public static void vehicleGroupUpdateBatchTest() {
        Test.startTest();
        Id testBatchJobId = Database.executeBatch(new VehicleGroupUpdateBatchable(), 200);
        Test.stopTest();
        Vehicle__c veh = [SELECT Vehicle_Group__r.Name FROM Vehicle__c WHERE ACRISS_Code__c = :TestUtilitySIXT.ACCRIS_CODE LIMIT 1];
        System.assertEquals(TestUtilitySIXT.VEHICLE_GROUP_NAME, veh.Vehicle_Group__r.Name, 'Vehicle Group has not been assigned or wrongly assigned!');
    }
}