force-app/main/default/objects/FleetManagementConfig__c/FleetManagementConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom config for Fleet Management app</description>
    <label>Fleet Management Config</label>
</CustomObject>

force-app/main/default/objects/FleetManagementConfig__c/fields/DefaultBatchId__c.field-meta.xml
<CustomField>
    <fullName>DefaultBatchId__c</fullName>
    <description>default batch that is used for example for vehicles created from AutoDesktop and not the normal flow</description>
    <inlineHelpText>default batch that is used for example for vehicles created from AutoDesktop and not the normal flow</inlineHelpText>
    <label>Default Batch Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FleetManagementConfig__c/fields/ExchangeVehicleGroupId__c.field-meta.xml
<CustomField>
    <fullName>ExchangeVehicleGroupId__c</fullName>
    <description>Id of the Vehicle Group that shall be used for Exchange vehicles as default</description>
    <inlineHelpText>Id of the Vehicle Group that shall be used for Exchange vehicles as default</inlineHelpText>
    <label>Exchange Vehicle Group Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>describe the reason for the batch</description>
    <inlineHelpText>describe the reason for the batch</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>to split batches that are from standard process and batches used for special purposes, like exchange cars from AutoDesktop</description>
    <inlineHelpText>to split batches that are from standard process and batches used for special purposes, like exchange cars from AutoDesktop</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NO LONGER REQUIRED as batch can include several groups
we are buying vehicles for this Vehicle Group</description>
    <inlineHelpText>we are buying vehicles for this Vehicle Group</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Vehicle Batches</relationshipLabel>
    <relationshipName>Vehicle_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateDefaultBatchSchedulable.cls
/**
 * This is a scheduled process that will create new vehicle batch record
 * and set this as new default batch for vehicles coming from non-standard process,
 * e.g. from AutoDesktop
 *
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Marek Smerak      <marek.smerak@wipro.com>
 * @modifiedBy     Marek Smerak      <marek.smerak@wipro.com>
 * @version        1.0
 * @created        2023-04-25
 * @modified       2023-04-25
 * @systemLayer    Scheduled Apex
 * @see            SIXT-106
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v1.0            marek.smerak@wipro.com
 * 2023-04-25      initial version
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
 */
public with sharing class CreateDefaultBatchSchedulable implements System.Schedulable {
    private static final String LABEL_FOR_DESCRIPTION = Label.Xfleet_Label_Default_Batch_Description;
    private static final String OPEN_BRACKET = '{{';
    private static final String CLOSE_BRACKET = '}}';

    public void execute(SchedulableContext sc) {
        // read the label
        // add Date part
        String dateFormat = LABEL_FOR_DESCRIPTION.substringBetween(OPEN_BRACKET, CLOSE_BRACKET);
        String dateString = System.now().format(dateFormat);
        String batchDescription = LABEL_FOR_DESCRIPTION.replace(OPEN_BRACKET + dateFormat + CLOSE_BRACKET, dateString);
        // crate a batch
        vehicleBatch__c newDefaultBatch = new vehicleBatch__c();
        newDefaultBatch.Description__c = batchDescription;
        newDefaultBatch.Type__c = 'Other';
        FleetManagementConfig__c config = FleetManagementConfig__c.getOrgDefaults();
        newDefaultBatch.Vehicle_Group__c = config.ExchangeVehicleGroupId__c; 
        insert newDefaultBatch;
        // update custom metadata
        config.DefaultBatchId__c = newDefaultBatch.Id;
        update config;
    }
}