force-app/main/default/objects/FleetManagementConfig__c/FleetManagementConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom config for Fleet Management app</description>
    <label>Fleet Management Config</label>
</CustomObject>

force-app/main/default/objects/FleetManagementConfig__c/fields/DefaultBatchId__c.field-meta.xml
<CustomField>
    <fullName>DefaultBatchId__c</fullName>
    <description>default batch that is used for example for vehicles created from AutoDesktop and not the normal flow</description>
    <inlineHelpText>default batch that is used for example for vehicles created from AutoDesktop and not the normal flow</inlineHelpText>
    <label>Default Batch Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>setting for using Integration Requests</description>
    <label>Xfleet Integration</label>
</CustomObject>

force-app/main/default/objects/IntegrationSettings__c/fields/Batch_Job_Delay_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Delay_in_minutes__c</fullName>
    <defaultValue>3</defaultValue>
    <description>integration job is scheduled to run after X minutes after &quot;trigger&quot;</description>
    <inlineHelpText>integration job is scheduled to run after X minutes after &quot;trigger&quot;</inlineHelpText>
    <label>Batch Job Delay (in minutes)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>How many Integration Request are processed in one batch run. Choose lower number if you have issue with timeout or limits.</description>
    <inlineHelpText>How many Integration Request are processed in one batch run. Choose lower number if you have issue with timeout or limits.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/fields/Job_last_run_at__c.field-meta.xml
<CustomField>
    <fullName>Job_last_run_at__c</fullName>
    <description>When the Integration Requests have been last processed.</description>
    <inlineHelpText>When the Integration Requests have been last processed.</inlineHelpText>
    <label>Job last run at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/License_plate__c.field-meta.xml
<CustomField>
    <fullName>License_plate__c</fullName>
    <label>License plate</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/REST_XfleetVehicle_Test.cls
@isTest
public class REST_XfleetVehicle_Test {
    private final static String TEST_VIN_NO = 'VR3FBYHZTMY528656';
    private final static String TEST_REG_NO = 'DF 75664';
    private final static String TEST_VIN_NO_2 = 'VR3FBYHZTMY522222';
    private final static String TEST_REG_NO_2 = 'AB75664';

    private static final Integer BATCH_DELAY = 5;
    private static final Integer BATCH_SIZE = 15;
    private static final Datetime LAST_JOB_RUN = Datetime.newInstance(2022, 11, 28, 5, 30, 0);

    @TestSetup
    static void makeData() {
        // custom settings
        TestUtilitySIXT.initFleetManagementSettings();

        IntegrationSettings__c testSettings = new IntegrationSettings__c();
        testSettings.Batch_Job_Delay_in_minutes__c = BATCH_DELAY;
        testSettings.Job_last_run_at__c = LAST_JOB_RUN;
        testSettings.Batch_Size__c = BATCH_SIZE;
        insert testSettings;

        // vehicles data
        vehicleBatch__c b = TestUtilitySIXT.createBatch();
        Map<String, Object> veh1Params = new Map<String, Object>{ 'vinNumber__c' => TEST_VIN_NO, 'License_Plate__c' => TEST_REG_NO };
        Vehicle__c v1 = TestUtilitySIXT.createVehicle(b.Id, veh1Params);

        FleetManagementConfig__c config = FleetManagementConfig__c.getOrgDefaults();
        config.DefaultBatchId__c = b.Id;
        update config;
    }

    @isTest
    public static void createVehicle() {
        // prepare request
        REST_XfleetVehicle.VehicleWrapper req = new REST_XfleetVehicle.VehicleWrapper();
        req.vin = TEST_VIN_NO_2;

        // REST request
        RestRequest restReq = new RestRequest();
        restReq.requestUri = 'https://yourInstance.my.salesforce.com/services/apexrest/Xfleet/v1/Vehicle';
        restReq.httpMethod = 'POST';
        //restReq.params.put('vehicle', JSON.serialize(req, true));
        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        Test.startTest();
        // process request
        REST_XfleetVehicle.doPost(req);
        Test.stopTest();

        System.assertEquals(201, RestContext.response.statusCode);
    }

    @isTest
    public static void getVehicle() {
        // vehicle id
        Vehicle__c v = [SELECT Id FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN_NO];

        // REST request
        RestRequest restReq = new RestRequest();
        restReq.requestUri = 'https://yourInstance.my.salesforce.com/services/apexrest/Xfleet/v1/Vehicle/' + v.Id;
        restReq.httpMethod = 'GET';
        //restReq.params.put('vehicle', JSON.serialize(req, true));
        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        Test.startTest();
        // process request
        REST_XfleetVehicle.doGet();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
    }

    @isTest
    public static void updateVehicle() {
        // vehicle id
        Vehicle__c v = [SELECT Id FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN_NO];

        // prepare request
        REST_XfleetVehicle.VehicleWrapper req = new REST_XfleetVehicle.VehicleWrapper();
        req.modelName = 'XC60';

        // REST request
        RestRequest restReq = new RestRequest();
        restReq.requestUri = 'https://yourInstance.my.salesforce.com/services/apexrest/Xfleet/v1/Vehicle/' + v.Id;
        restReq.httpMethod = 'PATCH';
        //restReq.params.put('vehicle', JSON.serialize(req, true));
        RestContext.request = restReq;
        RestContext.response = new RestResponse();

        Test.startTest();
        // process request
        REST_XfleetVehicle.doPatch(req);
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
    }
}