force-app/main/default/objects/Account/fields/EUR_DKK__c.field-meta.xml
<CustomField>
    <fullName>EUR_DKK__c</fullName>
    <label>EUR/DKK</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Automatic_gears__c.field-meta.xml
<CustomField>
    <fullName>Automatic_gears__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Autogear</description>
    <label>Automatic gears</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Bluetooth__c.field-meta.xml
<CustomField>
    <fullName>Bluetooth__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bluetooth</description>
    <label>Bluetooth</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alfa Romeo</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Citroën</fullName>
            </value>
            <value>
                <fullName>Cupra</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Land Rover</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mercedes Benz</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Opel</fullName>
            </value>
            <value>
                <fullName>Peugeot</fullName>
            </value>
            <value>
                <fullName>Polestar</fullName>
            </value>
            <value>
                <fullName>Porsche</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
            <value>
                <fullName>Seat</fullName>
            </value>
            <value>
                <fullName>Skoda</fullName>
            </value>
            <value>
                <fullName>Suzuki</fullName>
            </value>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>Volvo</fullName>
            </value>
            <value>
                <fullName>VW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/CO2__c.field-meta.xml
<CustomField>
    <fullName>CO2__c</fullName>
    <label>CO2 (g/km)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <label>Color</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Fuel_type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_type__c</fullName>
    <label>Fuel type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DI</fullName>
                <label>Diesel</label>
            </value>
            <value>
                <fullName>EL</fullName>
                <label>Electric</label>
            </value>
            <value>
                <fullName>HBBP</fullName>
                <label>Hybrid Petrol</label>
            </value>
            <value>
                <fullName>HBD</fullName>
                <label>Hybrid Diesel</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Petrol</label>
            </value>
            <value>
                <fullName>HBB</fullName>
                <label>Hybrid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/kmPrL__c.field-meta.xml
<CustomField>
    <fullName>kmPrL__c</fullName>
    <label>KM/L</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>What model is the car?</description>
    <inlineHelpText>What model is the car?</inlineHelpText>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Navigation__c.field-meta.xml
<CustomField>
    <fullName>Navigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Navi</description>
    <label>Navigation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Non_standard_Accessories__c.field-meta.xml
<CustomField>
    <fullName>Non_standard_Accessories__c</fullName>
    <description>Udstyr udover std.</description>
    <label>Non-standard Accessories</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>opportunity to sell the vehicle</description>
    <inlineHelpText>opportunity to sell the vehicle</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Parking_sensor__c.field-meta.xml
<CustomField>
    <fullName>Parking_sensor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>P-Sensor</description>
    <label>Parking sensor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Production_Number__c.field-meta.xml
<CustomField>
    <fullName>Production_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>vehicle production number, populated from file from Dealer</description>
    <label>Production Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Sales_Price_EUR__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price_EUR__c</fullName>
    <description>automatically calculated from Sales Price in DKK, rate can be set in the setup by admin</description>
    <formula>Sales_Price_Formula__c *  $Setup.ConversionRate__c.DKK_to_EUR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>automatically calculated from Sales Price in DKK, rate can be set in the setup by admin</inlineHelpText>
    <label>Estimated remarketing price EUR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Sales_Price_Formula__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price_Formula__c</fullName>
    <formula>Selected_Vehicle_Calculator__r.Remarketing_Price__c</formula>
    <label>Future Value (FV)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Speed_Pilot__c.field-meta.xml
<CustomField>
    <fullName>Speed_Pilot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Speed Pilot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VehiclesFromOpportunityController.cls
public with sharing class VehiclesFromOpportunityController {
    public String oppId { get; set; }

    public VehiclesFromOpportunityController() {
    }

    public List<Vehicle__c> getOpportunityVehicles() {
        List<Vehicle__c> opptyVehicles = [
            SELECT
                Production_Number__c,
                vinNumber__c,
                Brand__c,
                Model__c,
                color__c,
                Fuel_type__c,
                kmPrL__c,
                CO2__c,
                Navigation__c,
                Automatic_gears__c,
                Speed_Pilot__c,
                Parking_sensor__c,
                Bluetooth__c,
                Non_standard_Accessories__c,
                Sales_Price_Formula__c,
                Sales_Price_EUR__c
            FROM Vehicle__c
            WHERE Opportunity__c = :oppId
        ];
        return opptyVehicles;
    }

    public Boolean getIsEUR() {
        Boolean isEUR = false;
        if (oppId != null) {
            Opportunity opp = [SELECT Account.EUR_DKK__c FROM Opportunity WHERE Id = :oppId LIMIT 1];
            if (String.isNotBlank(opp.Account.EUR_DKK__c) && opp.Account.EUR_DKK__c == 'EUR') {
                isEUR = true;
            }
        }
        return isEUR;
    }
}