force-app/main/default/objects/Account/fields/EUR_DKK__c.field-meta.xml
<CustomField>
    <fullName>EUR_DKK__c</fullName>
    <label>EUR/DKK</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Navision_Account__c.field-meta.xml
<CustomField>
    <fullName>Navision_Account__c</fullName>
    <description>Account number from Navision</description>
    <label>Navision Account #</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>if needed specify data / request body</description>
    <inlineHelpText>if needed specify data / request body</inlineHelpText>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Last_Processing_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Processing_Time__c</fullName>
    <label>Last Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An account with record type Dealer</description>
    <label>Dealer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer/Importer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_Invoice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Invoice request for License Plate cost has been send to Navision</description>
    <inlineHelpText>Invoice request for License Plate cost has been send to Navision</inlineHelpText>
    <label>License Plate Invoice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_Is_Not_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_Is_Not_Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>License Plate invoice process was run, but because of related Dealer we are not sending invoice (e.g. Dealer is out of DK)</description>
    <inlineHelpText>License Plate invoice process was run, but because of related Dealer we are not sending invoice (e.g. Dealer is out of DK)</inlineHelpText>
    <label>License Plate Is Not Invoiced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/licensePlateCost__c.field-meta.xml
<CustomField>
    <fullName>licensePlateCost__c</fullName>
    <label>License Plate Cost</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NAVSendLicensePlateInvoiceSchedulable.cls
public with sharing class NAVSendLicensePlateInvoiceSchedulable implements System.Schedulable {
    private static final String ERROR_MSG_BAD_DATA = 'License plate cost or dealer navision number is missing';
    private static final String QUERY_VEHICLES = Label.Xfleet_Query_Vehicles_for_License_Plate_Invoice;
    private static final String LABEL_INVOICE_DESCRIPTION = Label.Xfleet_Label_License_Plate_Invoice_Description;

    public NAVSendLicensePlateInvoiceSchedulable() {
    }

    public void execute(SchedulableContext sc) {
        // get newly registered vehicles where invoice hasn't been sent yet
        List<Vehicle__c> vehicles = Database.query(QUERY_VEHICLES, AccessLevel.SYSTEM_MODE);
        // and create Integration Request for them
        List<Integration_Request__c> irs = new List<Integration_Request__c>();
        for (Vehicle__c v : vehicles) {
            // do not invoice EUR dealers
            if (v.Dealer__r.EUR_DKK__c == 'EUR') {
                v.License_Plate_Is_Not_Invoiced__c = true;
            } else {
                // create integration request for DK dealers
                irs.add(createLicensePlateInvoiceRequest(v));
            }
            // mark vehicle as processed
            v.License_Plate_Invoice_Sent__c = true;
        }
        insert irs;
        // mark vehicles as License Plate Invoice request sent
        update vehicles;
    }

    public static Integration_Request__c createLicensePlateInvoiceRequest(Vehicle__c v) {
        Integration_Request__c ir = new Integration_Request__c();
        ir.Vehicle__c = v.Id;
        ir.API_Method__c = IntegrationRequestsNAVCars.METHOD_INVOICE;
        // invoice description
        String invoiceDescription = UtilityCommon.mergeFieldsIntoString(LABEL_INVOICE_DESCRIPTION, v);
        NAVCarsObject navCar = new NAVCarsObject(
            v.licensePlateCost__c,
            null,
            v.Dealer__r.Navision_Account__c,
            null,
            1,
            false,
            invoiceDescription,
            null,
            null,
            true
        );
        ir.Data__c = JSON.serialize(navCar, true);
        // if some data are missing mark the requested as failed
        if (v.licensePlateCost__c == null || v.Dealer__c == null || String.isBlank(v.Dealer__r.Navision_Account__c)) {
            ir.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            ir.Message__c = ERROR_MSG_BAD_DATA;
            ir.Last_Processing_Time__c = System.now();
        }
        return ir;
    }
}