force-app/main/default/objects/Account/fields/Leasing_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Algorithm__c</fullName>
    <description>type of algorithm that is used by this leasing partner
1 - PMT (or PMT + L94)</description>
    <inlineHelpText>type of algorithm that is used by this leasing partner
1 - PMT (or PMT + L94)</inlineHelpText>
    <label>Leasing Algorithm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Batch_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Batch_Distribution__c</fullName>
    <label>Batch Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valutacar</fullName>
            </value>
            <value>
                <fullName>DK-car</fullName>
            </value>
            <value>
                <fullName>Mini-lease</fullName>
            </value>
            <value>
                <fullName>Full-tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Current_Month_in_Leasing__c.field-meta.xml
<CustomField>
    <fullName>Current_Month_in_Leasing__c</fullName>
    <description>based on registration date, shows in which month of leasing period the vehicle currently is</description>
    <formula>/* To find the number of months between two dates, subtract the year of the earlier date from the year of the later date and multiply the difference by 12. 
 * Next, subtract the month of the earlier date from the month of the later date, and add that difference to the value of the first set of operations. 
	* ((YEAR(date_1) - YEAR(date_2))*12) + (MONTH(date_1) - MONTH(date_2))
	*/
((YEAR(TODAY()) - YEAR(First_Registration_Date__c))*12) + (MONTH(TODAY()) - MONTH(First_Registration_Date__c))</formula>
    <inlineHelpText>based on registration date, shows in which month of leasing period the vehicle currently is</inlineHelpText>
    <label>Current Month in Leasing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Final_tax_after_deduction__c.field-meta.xml
<CustomField>
    <fullName>Final_tax_after_deduction__c</fullName>
    <description>Endelig afgift efter fradrag</description>
    <label>Final tax after deduction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/leasing_Account__c.field-meta.xml
<CustomField>
    <fullName>leasing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leasing Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select leasing company</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Leasing Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>VehiclesLeasing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Leasing_Cost_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Cost_Per_Month__c</fullName>
    <description>leasing cost per regular (2nd-Nth) month,
calculated in Apex based on Leasing Company algorithm</description>
    <inlineHelpText>leasing cost per regular (2nd-Nth) month</inlineHelpText>
    <label>Leasing Cost Per Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Leasing_Rate_Contract__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Rate_Contract__c</fullName>
    <description>Leasing interest rate specified with the contract with the Leasing Company</description>
    <formula>IF(ISPICKVAL(Batch_Distribution__c, &quot;Valutacar&quot;),
			 Leasing_Rate_Contract_Valuta__c,
			 Leasing_Rate_Contract_L94__c
)</formula>
    <inlineHelpText>Leasing interest rate specified with the contract with the Leasing Company</inlineHelpText>
    <label>Leasing Rate - Contract</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Redemption_Price_to_Leasing_Account__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Price_to_Leasing_Account__c</fullName>
    <description>Redemption price to finance company</description>
    <inlineHelpText>Redemption price to finance company</inlineHelpText>
    <label>Redemption Price to Leasing Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Total_Buy_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Buy_Price__c</fullName>
    <description>depends on tax type</description>
    <formula>/* depends on tax type */
IF(ISPICKVAL(Batch_Distribution__c, &quot;DK - Full tax&quot;),
   Tax_Base__c,
			Sixt_steel_purchase_price__c +  licensePlateCost__c + Delivery_cost__c + handlingCost__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>depends on tax type, if Full Tax then equals to Tax Base, otherwise it is (Sixt steel purchase price
 + License Plate Cost + Delivery Cost + Handling Cost)</inlineHelpText>
    <label>Total Buy Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CalculationsLeasingResidualValueBatch.cls
public with sharing class CalculationsLeasingResidualValueBatch implements Schedulable, Database.Batchable<SObject>, Database.Stateful {
    @TestVisible
    private static final String DEFAULT_QUERY = Label.Xfleet_Query_Vehicles_for_Residual_Value_Update;

    private String query;
    public Integer numberOfUpdatedVehicles;

    public CalculationsLeasingResidualValueBatch(String query) {
        this.query = query;
        this.numberOfUpdatedVehicles = 0;
    }

    public CalculationsLeasingResidualValueBatch() {
        this.query = DEFAULT_QUERY;
        this.numberOfUpdatedVehicles = 0;
    }

    // schedulable execute
    public void execute(SchedulableContext param1) {
        Database.executeBatch(new CalculationsLeasingResidualValueBatch());
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    // batchable execute
    public void execute(Database.BatchableContext bc, List<Vehicle__c> scope) {
        // get calculation inputs and calculate residual value
        List<CalculationsLeasingResidualValue.CalculationResidualValueInputs> calcInputs = convertVehicleToCalcInputs(scope);
        List<CalculationsLeasingResidualValue.CalculationResidualValueOutputs> calcOutputs = CalculationsLeasingResidualValue.calculateResidualValue(
            calcInputs
        );
        for (Integer i = 0; i < scope.size(); i++) {
            Vehicle__c v = scope.get(i);
            v.Redemption_Price_to_Leasing_Account__c = calcOutputs.get(i).residualValue;
        }
        // update vehicles in scope
        update scope;
        this.numberOfUpdatedVehicles += scope.size();
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Update Residual Value finished, updated ' + this.numberOfUpdatedVehicles + ' updated!');
    }

    private List<CalculationsLeasingResidualValue.CalculationResidualValueInputs> convertVehicleToCalcInputs(List<Vehicle__c> vehs) {
        List<CalculationsLeasingResidualValue.CalculationResidualValueInputs> inputs = new List<CalculationsLeasingResidualValue.CalculationResidualValueInputs>();
        for (Vehicle__c v : vehs) {
            CalculationsLeasingResidualValue.CalculationResidualValueInputs singleInput = new CalculationsLeasingResidualValue.CalculationResidualValueInputs();
            singleInput.algorithm = Integer.valueOf(v.leasing_Account__r.Leasing_Algorithm__c);
            singleInput.interestRate = v.Leasing_Rate_Contract__c / 100;
            singleInput.isL94 = v.Batch_Distribution__c == 'DK - L94';
            singleInput.monthlyPayment = v.Leasing_Cost_Per_Month__c;
            singleInput.periodLength = Integer.valueOf(v.Current_Month_in_Leasing__c);
            singleInput.presentValue = v.Total_Buy_Price__c;
            singleInput.registrationBaseL94 = v.Final_tax_after_deduction__c;
            inputs.add(singleInput);
        }
        return inputs;
    }
}