force-app/main/default/objects/Account/fields/Leasing_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Algorithm__c</fullName>
    <description>type of algorithm that is used by this leasing partner
1 - PMT (or PMT + L94)</description>
    <inlineHelpText>type of algorithm that is used by this leasing partner
1 - PMT (or PMT + L94)</inlineHelpText>
    <label>Leasing Algorithm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Leasing_Rate__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Rate__c</fullName>
    <label>Leasing Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Batch_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Batch_Distribution__c</fullName>
    <label>Batch Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valutacar</fullName>
            </value>
            <value>
                <fullName>DK-car</fullName>
            </value>
            <value>
                <fullName>Mini-lease</fullName>
            </value>
            <value>
                <fullName>Full-tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/leasing_Account__c.field-meta.xml
<CustomField>
    <fullName>leasing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leasing Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select leasing company</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Leasing Company</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>VehiclesLeasing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Leasing_Cost_Per_Month__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Cost_Per_Month__c</fullName>
    <description>leasing cost per regular (2nd-Nth) month,
calculated in Apex based on Leasing Company algorithm</description>
    <inlineHelpText>leasing cost per regular (2nd-Nth) month</inlineHelpText>
    <label>Leasing Cost Per Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Redemption_Price_to_Leasing_Account__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Price_to_Leasing_Account__c</fullName>
    <description>Redemption price to finance company</description>
    <inlineHelpText>Redemption price to finance company</inlineHelpText>
    <label>Redemption Price to Leasing Account</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Sixt_steel_purchase_price__c.field-meta.xml
<CustomField>
    <fullName>Sixt_steel_purchase_price__c</fullName>
    <description>Sixt Indkøbspris stål</description>
    <label>Sixt steel purchase price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CalculationsLeasingResidualValueBatchTes.cls
@isTest
public with sharing class CalculationsLeasingResidualValueBatchTes {
    @isTest
    public static void residualValueBatch() {
        // prepare data
        Account testLeasingAccount = new Account(Name = 'Test Unit Leasing ACC1', Leasing_Algorithm__c = '1', Leasing_Rate__c = 3.75);
        insert testLeasingAccount;
        VehicleBatch__c testBatch = TestUtilitySIXT.createBatch();
        Map<String, Object> params = new Map<String, Object>();
        params.put('Batch_Distribution__c', 'Valuta');
        params.put('Leasing_Cost_Per_Month__c', 3284.43);
        params.put('Registration_Date__c', Date.today().addMonths(-1));
        params.put('Sixt_steel_purchase_price__c', 254330);
        Vehicle__c testVehicle = TestUtilitySIXT.createVehicle(testBatch.id, params);
        testVehicle.leasing_Account__c = testLeasingAccount.id;
        update testVehicle;

        // run test
        Test.startTest();
        SchedulableContext context;
        new CalculationsLeasingResidualValueBatch().execute(context);
        Test.stopTest();

        Vehicle__c testVehicleAfter = [SELECT Redemption_Price_to_Leasing_Account__c FROM Vehicle__c WHERE Id = :testVehicle.Id LIMIT 1];
        System.assertEquals(251830.1, testVehicleAfter.Redemption_Price_to_Leasing_Account__c.setScale(1));
    }
}