force-app/main/default/objects/Account/fields/Navision_Account__c.field-meta.xml
<CustomField>
    <fullName>Navision_Account__c</fullName>
    <description>Account number from Navision</description>
    <label>Navision Account #</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>if needed specify data / request body</description>
    <inlineHelpText>if needed specify data / request body</inlineHelpText>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An account with record type Dealer</description>
    <label>Dealer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer/Importer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_plate__c.field-meta.xml
<CustomField>
    <fullName>License_plate__c</fullName>
    <label>License plate</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_Invoice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Invoice request for License Plate cost has been send to Navision</description>
    <inlineHelpText>Invoice request for License Plate cost has been send to Navision</inlineHelpText>
    <label>License Plate Invoice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/licensePlateCost__c.field-meta.xml
<CustomField>
    <fullName>licensePlateCost__c</fullName>
    <label>License Plate Cost</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NAVSendLicensePlateInvoceSchedulable.cls
public with sharing class NAVSendLicensePlateInvoceSchedulable implements System.Schedulable {
    public NAVSendLicensePlateInvoceSchedulable() {
    }

    public void execute(SchedulableContext sc) {
        // get newly registered vehicles where invoice hasn't been sent yet
        List<Vehicle__c> vehicles = [
            SELECT LicensePlateCost__c, License_Plate_Invoice_Sent__c, Dealer__r.Navision_Account__c
            FROM Vehicle__c
            WHERE License_plate__c != NULL AND License_Plate_Invoice_Sent__c = FALSE
            LIMIT 5000
        ];
        // and create Integration Request for them
        List<Integration_Request__c> irs = new List<Integration_Request__c>();
        for (Vehicle__c v : vehicles) {
            irs.add(createLicensePlateInvoiceRequest(v));
            v.License_Plate_Invoice_Sent__c = true;
        }
        insert irs;
        // mark vehicles as License Plate Invoice request sent
        update vehicles;
    }

    public static Integration_Request__c createLicensePlateInvoiceRequest(Vehicle__c v) {
        Integration_Request__c ir = new Integration_Request__c();
        ir.Vehicle__c = v.Id;
        ir.API_Method__c = NAVCarsIntegrationBatchable.METHOD_INVOICE;
        NAVCarsObject navCar = new NAVCarsObject(v.licensePlateCost__c, null, v.Dealer__r.Navision_Account__c, null, 1, true);
        ir.Data__c = JSON.serialize(navCar, true);
        return ir;
    }
}