force-app/main/default/objects/Fleet_Overview__c/Fleet_Overview__c.object-meta.xml
<CustomObject>
    <label>Fleet Overview</label>
    <nameField>
        <label>Fleet Overview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Overview</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Overview__c/fields/City_name__c.field-meta.xml
<CustomField>
    <fullName>City_name__c</fullName>
    <label>City name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Import_Date__c.field-meta.xml
<CustomField>
    <fullName>Import_Date__c</fullName>
    <label>Import Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <label>Internal No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/KM__c.field-meta.xml
<CustomField>
    <fullName>KM__c</fullName>
    <label>KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Sixt_model__c.field-meta.xml
<CustomField>
    <fullName>Sixt_model__c</fullName>
    <label>Sixt model</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Veh_status__c.field-meta.xml
<CustomField>
    <fullName>Veh_status__c</fullName>
    <label>Veh. status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CobraFleetOverview2VehicleBatch.cls
public with sharing class CobraFleetOverview2VehicleBatch implements Database.Batchable<Fleet_Overview__c>, Database.Stateful {
    private Date importDate;
    public Integer numberOfUpdatedVehicles;

    public CobraFleetOverview2VehicleBatch(Date batchImportDate) {
        this.importDate = batchImportDate;
        this.numberOfUpdatedVehicles = 0;
    }

    public List<Fleet_Overview__c> start(Database.BatchableContext bc) {
        // get all from last import
        List<Fleet_Overview__c> fleets = [
            SELECT City_name__c, Description__c, Internal_No__c, KM__c, Registration__c, Sixt_model__c, Veh_status__c
            FROM Fleet_Overview__c
            WHERE Import_Date__c = :this.importDate
        ];
        return fleets;
    }

    public void execute(Database.BatchableContext bc, List<Fleet_Overview__c> scope) {
        // run the update
        Map<Decimal, Vehicle__c> vehicles = CobraFleetOverview2VehicleUtility.updateVehiclesFromFleetOverviewList(scope, true, true);
        numberOfUpdatedVehicles += vehicles.size(); 
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Update from Fleet Overview batch finished, updated ' + this.numberOfUpdatedVehicles + ' updated!');
        
    }
}