force-app/main/default/objects/Fleet_Overview__c/Fleet_Overview__c.object-meta.xml
<CustomObject>
    <label>Fleet Overview</label>
    <nameField>
        <label>Fleet Overview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Overview</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Overview__c/fields/Import_Date__c.field-meta.xml
<CustomField>
    <fullName>Import_Date__c</fullName>
    <label>Import Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CobraFleetOverview2VehicleScheduler.cls
public with sharing class CobraFleetOverview2VehicleScheduler implements Schedulable {
    public void execute(SchedulableContext SC) {
        // get last import date
        Fleet_Overview__c lastRecord = [SELECT Import_Date__c FROM Fleet_Overview__c ORDER BY Import_Date__c DESC LIMIT 1];
        System.debug('last Fleet Overview import date: ' + lastRecord.Import_Date__c);
        // execute batch job
        CobraFleetOverview2VehicleBatch updateFromFleetOverviewJob = new CobraFleetOverview2VehicleBatch(lastRecord.Import_Date__c);
        ID batchJobId = Database.executeBatch(updateFromFleetOverviewJob);
    }
}