force-app/main/default/objects/Fleet_Overview__c/Fleet_Overview__c.object-meta.xml
<CustomObject>
    <label>Fleet Overview</label>
    <nameField>
        <label>Fleet Overview</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Overview</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Overview__c/fields/City_name__c.field-meta.xml
<CustomField>
    <fullName>City_name__c</fullName>
    <label>City name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Import_Date__c.field-meta.xml
<CustomField>
    <fullName>Import_Date__c</fullName>
    <label>Import Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Internal_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_No__c</fullName>
    <label>Internal No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/KM__c.field-meta.xml
<CustomField>
    <fullName>KM__c</fullName>
    <label>KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Sixt_model__c.field-meta.xml
<CustomField>
    <fullName>Sixt_model__c</fullName>
    <label>Sixt model</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Overview__c/fields/Veh_status__c.field-meta.xml
<CustomField>
    <fullName>Veh_status__c</fullName>
    <label>Veh. status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Current_city__c.field-meta.xml
<CustomField>
    <fullName>Current_city__c</fullName>
    <label>Current city</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Current_KM__c.field-meta.xml
<CustomField>
    <fullName>Current_KM__c</fullName>
    <label>Current KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Internal_number__c.field-meta.xml
<CustomField>
    <fullName>Internal_number__c</fullName>
    <externalId>true</externalId>
    <label>Internal Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_plate__c.field-meta.xml
<CustomField>
    <fullName>License_plate__c</fullName>
    <label>License plate</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_status__c</fullName>
    <description>status of the vehicle in COBRA</description>
    <inlineHelpText>status of the vehicle in COBRA</inlineHelpText>
    <label>Vehicle status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - Car is rented</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Car is ready for rental</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 - Default</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 - Car is not ready, block for a reservation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 - Car is available, but not cleaned</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 - Car is not available, blocked for workshop etc.</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6 - Car is on workshop</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10 - Car arrived, but not checked in yet</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Car is checked in, but rental agreement not closed</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 - Car is blocked for sale</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 - Car is on station, but not on contract</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>99 - Car is on checkout</label>
            </value>
            <value>
                <fullName>00-</fullName>
                <label>00- - Car is defleeted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>describe the reason for the batch</description>
    <inlineHelpText>describe the reason for the batch</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CobraFleetOverview2Vehicle_Test.cls
@isTest
public with sharing class CobraFleetOverview2Vehicle_Test {
    private static final Decimal INTERNAL_NUMBER_1 = 100;
    private static final String LICENSE_PLATE_1 = 'ABC001';
    private static final Decimal CURRENT_KM_1 = 1200;

    private static final Decimal INTERNAL_NUMBER_2 = 101;
    private static final String LICENSE_PLATE_2 = 'MRK007';
    private static final Decimal CURRENT_KM_2 = 2500;

    private static final Decimal INTERNAL_NUMBER_3 = 102;
    private static final String LICENSE_PLATE_3 = 'MRK10A';
    private static final Decimal CURRENT_KM_3 = 2500;
    private static final String COBRA_DEFLEETED_STATUS = '00-';

    @TestSetup
    static void makeData() {
        // Vehicles
        VehicleBatch__c testBatch = TestUtilitySIXT.createBatch();
        Map<String, Object> testVehicleParams = new Map<String, Object>{ 'Internal_Number__c' => INTERNAL_NUMBER_1 };
        TestUtilitySIXT.createVehicle(testBatch.Id, testVehicleParams);
        Map<String, Object> test2ndVehicleParams = new Map<String, Object>{ 'License_Plate__c' => LICENSE_PLATE_2 };
        TestUtilitySIXT.createVehicle(testBatch.Id, test2ndVehicleParams);
        // 3rd vehicle is in Cobra defleeted status already
        Map<String, Object> test3rdVehicleParams = new Map<String, Object>{
            'Internal_Number__c' => INTERNAL_NUMBER_3,
            'Current_KM__c' => CURRENT_KM_3,
            'License_Plate__c' => LICENSE_PLATE_3,
            'Vehicle_Status__c' => COBRA_DEFLEETED_STATUS
        };
        TestUtilitySIXT.createVehicle(testBatch.Id, test3rdVehicleParams);

        // Fleet Overviews
        Date importDate = Date.today();

        Fleet_Overview__c fo1 = new Fleet_Overview__c();
        fo1.City_name__c = 'Praha ha ha';
        fo1.KM__c = CURRENT_KM_1;
        fo1.Description__c = 'unit test car 100';
        fo1.Internal_No__c = INTERNAL_NUMBER_1;
        fo1.Registration__c = LICENSE_PLATE_1;
        fo1.Sixt_model__c = 123;
        fo1.Veh_status__c = 0;
        fo1.Import_Date__c = importDate;
        insert fo1;

        Fleet_Overview__c fo2 = new Fleet_Overview__c();
        fo2.City_name__c = 'Praha hi hi';
        fo2.KM__c = CURRENT_KM_2;
        fo2.Description__c = 'unit test car MRK007';
        fo2.Internal_No__c = INTERNAL_NUMBER_2;
        fo2.Registration__c = LICENSE_PLATE_2;
        fo2.Sixt_model__c = 123;
        fo2.Veh_status__c = 0;
        fo2.Import_Date__c = importDate;
        insert fo2;

        Fleet_Overview__c fo3 = new Fleet_Overview__c();
        fo3.City_name__c = 'Praha hi hi';
        fo3.KM__c = CURRENT_KM_3 - 100;
        fo3.Description__c = 'unit test car MRK10A';
        fo3.Internal_No__c = INTERNAL_NUMBER_3;
        fo3.Registration__c = LICENSE_PLATE_3;
        fo3.Sixt_model__c = 123;
        fo3.Veh_status__c = 0;
        fo3.Import_Date__c = importDate;
        insert fo3;
    }

    @isTest
    public static void onlyByInternalNumber() {
        List<Fleet_Overview__c> testFleetOverviews = [
            SELECT City_name__c, Description__c, Internal_No__c, KM__c, Registration__c, Sixt_model__c, Veh_status__c
            FROM Fleet_Overview__c
        ];

        Map<Decimal, Vehicle__c> testResults = CobraFleetOverview2VehicleUtility.updateVehiclesFromFleetOverviewList(testFleetOverviews, false, false);
        System.assertEquals(1, testResults.size());
        System.assert(testResults.containsKey(INTERNAL_NUMBER_1));
    }

    @isTest
    public static void usingLisencePlateToo() {
        List<Fleet_Overview__c> testFleetOverviews = [
            SELECT City_name__c, Description__c, Internal_No__c, KM__c, Registration__c, Sixt_model__c, Veh_status__c
            FROM Fleet_Overview__c
        ];

        Map<Decimal, Vehicle__c> testResults = CobraFleetOverview2VehicleUtility.updateVehiclesFromFleetOverviewList(testFleetOverviews, true, false);
        System.assertEquals(2, testResults.size());
        System.assert(testResults.containsKey(INTERNAL_NUMBER_1));
        System.assert(testResults.containsKey(INTERNAL_NUMBER_2));
    }

    // scheduler
    @isTest
    public static void cobraUpdateFromFleetOverviewScheduler() {
        String nextYear = String.valueOf(Date.today().year() + 1);
        Test.startTest();
        Id schedulerJobId = System.schedule('unitTestCobraFromFOUpdate', '0 0 0 1 1 ? ' + nextYear, new CobraFleetOverview2VehicleScheduler());
        Test.stopTest();
    }

    // test of batch class and process
    @isTest
    public static void cobraUpdateFromFleetOverviewBatch() {
        Test.startTest();
        Id testBatchJobId = Database.executeBatch(new CobraFleetOverview2VehicleBatch(Date.today()), 200);
        Test.stopTest();
        Vehicle__c veh1 = [SELECT Current_city__c, Current_KM__c FROM Vehicle__c WHERE Internal_number__c = :INTERNAL_NUMBER_1];
        System.assertEquals(CURRENT_KM_1, veh1.Current_KM__c, 'Kilometers not updated correctly on Vehicle 1');
        Vehicle__c veh2 = [SELECT Current_city__c, Current_KM__c FROM Vehicle__c WHERE Internal_number__c = :INTERNAL_NUMBER_2];
        System.assertEquals(CURRENT_KM_2, veh2.Current_KM__c, 'Kilometers not updated correctly on Vehicle 2');
        Vehicle__c veh3 = [SELECT Vehicle_Status__c, Current_KM__c FROM Vehicle__c WHERE Internal_number__c = :INTERNAL_NUMBER_3];
        System.assertEquals(CURRENT_KM_3, veh3.Current_KM__c, 'Kilometers shall not be updated on Vehicle 3');
        System.assertEquals(COBRA_DEFLEETED_STATUS, veh3.Vehicle_Status__c, 'Vehicle Status shall not be updated on Vehicle 3');
    }
}