force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>if needed specify data / request body</description>
    <inlineHelpText>if needed specify data / request body</inlineHelpText>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Batch_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Batch_Distribution__c</fullName>
    <label>Batch Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valutacar</fullName>
            </value>
            <value>
                <fullName>DK-car</fullName>
            </value>
            <value>
                <fullName>Mini-lease</fullName>
            </value>
            <value>
                <fullName>Full-tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_plate__c.field-meta.xml
<CustomField>
    <fullName>License_plate__c</fullName>
    <label>License plate</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_System__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_System__c</fullName>
    <description>License Plate / Registration Number in official format used with SKAT and with external communication or integration</description>
    <externalId>true</externalId>
    <inlineHelpText>License Plate / Registration Number in official format used with SKAT</inlineHelpText>
    <label>License Plate (System)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationRequestsNAVCars_Test.cls
@isTest
public class IntegrationRequestsNAVCars_Test {
    public static final String TEST_VIN = 'VINUNIT78364';
    public static final String TEST_REG_NUM = 'RN 12345';

    private final static String MOCK_SINGLE_CAR = 'NAVCars_SingleCarResponse';
    private final static String MOCK_MULTIPLE_CARS = 'NAVCars_MultipleCarResponse';
    private final static String MOCK_ERROR = 'NAVCars_ErrorResponse';

    @TestSetup
    static void makeData() {
        // Xfleet dependency on Vehicle__c
        Map<String, Object> vehParams = new Map<String, Object>{ 'vinNumber__c' => TEST_VIN, 'license_plate__c' => TEST_REG_NUM };
        Vehicle__c testVehicle = TestUtilitySIXT.createVehicle(TestUtilitySIXT.createBatch().Id, vehParams);
    }

    @isTest
    public static void createMethodTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_SINGLE_CAR);
        mock.setStatusCode(201);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = [SELECT vinNumber__c, License_plate_System__c, Batch_Distribution__c FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN];
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsNAVCars.METHOD_CREATE;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsNAVCars testProcessor = new IntegrationRequestsNAVCars();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void updateMethodTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_SINGLE_CAR);
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = [SELECT vinNumber__c, License_plate_System__c, Batch_Distribution__c FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN];
        veh.Batch_Distribution__c = 'DK - Tax type not determined';
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsNAVCars.METHOD_UPDATE;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsNAVCars testProcessor = new IntegrationRequestsNAVCars();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void invoiceMethodTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_SINGLE_CAR);
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = [SELECT vinNumber__c, License_plate_System__c, Batch_Distribution__c FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN];
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsNAVCars.METHOD_INVOICE;
        ir.Vehicle__c = veh.Id;
        // construct data
        NAVCarsObject theData = new NAVCarsObject(125000, 'unittestNAV2367', 'B028232', null, 1, false);
        ir.Data__c = JSON.serialize(theData, true);
        // test request processing
        IntegrationRequestsNAVCars testProcessor = new IntegrationRequestsNAVCars();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void createMethodTestNegative() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_ERROR);
        mock.setStatusCode(401);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = [SELECT vinNumber__c, License_plate_System__c, Batch_Distribution__c FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN];
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsNAVCars.METHOD_CREATE;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsNAVCars testProcessor = new IntegrationRequestsNAVCars();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_FAILED, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void methodNotSupportedNegative() {
        Vehicle__c veh = [SELECT vinNumber__c, License_plate_System__c, Batch_Distribution__c FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN];
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = 'UnitTest';
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsNAVCars testProcessor = new IntegrationRequestsNAVCars();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_FAILED, ir.Status__c, 'Wrong status set!');
    }
}