force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>if needed specify data / request body</description>
    <inlineHelpText>if needed specify data / request body</inlineHelpText>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Last_Processing_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Processing_Time__c</fullName>
    <label>Last Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Batch_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Batch_Distribution__c</fullName>
    <label>Batch Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valutacar</fullName>
            </value>
            <value>
                <fullName>DK-car</fullName>
            </value>
            <value>
                <fullName>Mini-lease</fullName>
            </value>
            <value>
                <fullName>Full-tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Car_description_2__c.field-meta.xml
<CustomField>
    <fullName>Car_description_2__c</fullName>
    <formula>TEXT(Brand__c) + &quot; &quot; +  Model__c + &quot; &quot; +  License_plate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Car description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Current_KM__c.field-meta.xml
<CustomField>
    <fullName>Current_KM__c</fullName>
    <label>Current KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_Plate_System__c.field-meta.xml
<CustomField>
    <fullName>License_Plate_System__c</fullName>
    <description>License Plate / Registration Number in official format used with SKAT and with external communication or integration</description>
    <externalId>true</externalId>
    <inlineHelpText>License Plate / Registration Number in official format used with SKAT</inlineHelpText>
    <label>License Plate (System)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationRequestsNAVCars.cls
public with sharing class IntegrationRequestsNAVCars implements IntegrationRequestsProcess{

    public static final String METHOD_CREATE = 'NAV-createCar';
    public static final String METHOD_UPDATE = 'NAV-updateCar';
    public static final String METHOD_INVOICE = 'NAV-createInvoiceQuote';
    public static final String METHOD_INVOICE_CARS_PRIVATE = 'NAV-createInvoicePrivate';

    
    public Integration_Request__c process(Integration_Request__c req, Vehicle__c veh) {
        NAVCars navApi;
        // CREATE
        if (req.API_Method__c.equals(METHOD_CREATE)) {
            navApi = new NAVCarsCreate();
        } else if (req.API_Method__c.equals(METHOD_UPDATE)) {
            // UPDATE
            navApi = new NAVCarsUpdate(veh.vinNumber__c);
        } else if (req.API_Method__c.equals(METHOD_INVOICE)) {
            // UPDATE - Create Invoice or Quote
            navApi = new NAVCarsUpdate(veh.vinNumber__c);
        } else if (req.API_Method__c.equals(METHOD_INVOICE_CARS_PRIVATE)) {
            // UPDATE - Create Invoice or Quote
            navApi = new NAVCarsUpdate(veh.vinNumber__c, NAVCars.CARS_PRIVATE_API);
        }

        // is method supported?
        if (navApi != null) {
            // prepare data and call API
            NAVCarsObject theCar;
            // are data already prepared in the request record?
            if (String.isNotBlank(req.Data__c)) {
                theCar = (NAVCarsObject)JSON.deserialize(req.Data__c, NAVCarsObject.class);
            } else {
                theCar = new NAVCarsObject(veh.vinNumber__c, veh.License_Plate_System__c, veh.Batch_Distribution__c, veh.Car_description_2__c, (Integer)veh.Current_KM__c);
                req.Data__c = JSON.serialize(theCar, true);
            }
            HttpRequest navApiReq = navApi.prepareRequest(theCar);
            HttpResponse navApiResp = navApi.call(navApiReq);
            // is it success?
            Integer statusCode = navApiResp.getStatusCode();
            if ((statusCode == 200) || (statusCode == 201)) {
                // SUCCESS
                req.Status__c = IntegrationRequestsUtility.STATUS_SUCCESS;
            } else {
                req.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            }
            // add message
            req.Message__c = constructResponseMessage(navApiResp);
        } else {
            req.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            req.Message__c = IntegrationRequestsBatchable.ERROR_WRONG_METHOD;
        }
        // set Integration Request processed timestamp
        req.Last_Processing_Time__c = System.now();
        // return the updated req
        return req;
    }

    private String constructResponseMessage(HttpResponse httpResp) {
        String message = '[' + httpResp.getStatusCode() + ', ' + httpResp.getStatus() + ']';
        if (String.isNotBlank(httpResp.getBody())) {
            message += '\n' + httpResp.getBody();
        }
        return message;
    }
}