force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>setting for using Integration Requests</description>
    <label>Xfleet Integration</label>
</CustomObject>

force-app/main/default/objects/IntegrationSettings__c/fields/Batch_Job_Delay_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Delay_in_minutes__c</fullName>
    <defaultValue>3</defaultValue>
    <description>integration job is scheduled to run after X minutes after &quot;trigger&quot;</description>
    <inlineHelpText>integration job is scheduled to run after X minutes after &quot;trigger&quot;</inlineHelpText>
    <label>Batch Job Delay (in minutes)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/fields/Job_last_run_at__c.field-meta.xml
<CustomField>
    <fullName>Job_last_run_at__c</fullName>
    <description>When the Integration Requests have been last processed.</description>
    <inlineHelpText>When the Integration Requests have been last processed.</inlineHelpText>
    <label>Job last run at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Integration_Requests_Number_Failed__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requests_Number_Failed__c</fullName>
    <description>System rollup field that display number of Integration Request related to the vehicle and processed with ERROR.</description>
    <inlineHelpText>System rollup field that display number of Integration Request related to the vehicle and processed with ERROR.</inlineHelpText>
    <label>Integration Requests Number - Failed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Integration_Requests_Number_Not_Run_Yet__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requests_Number_Not_Run_Yet__c</fullName>
    <description>System rollup field that display number of Integration Request related to the vehicle and that have not been processed yet.</description>
    <inlineHelpText>System rollup field that display number of Integration Request related to the vehicle and that have not been processed yet.</inlineHelpText>
    <label>Integration Requests Number -Not Run Yet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Integration_Requests_Number_Success__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requests_Number_Success__c</fullName>
    <description>System rollup field that display number of Integration Request related to the vehicle and processed successfully.</description>
    <inlineHelpText>System rollup field that display number of Integration Request related to the vehicle and processed successfully.</inlineHelpText>
    <label>Integration Requests Number - Success</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationRequestsUtility.cls
public with sharing class IntegrationRequestsUtility {
    public static final String BATCH_JOB_APEX_NAME = 'IntegrationRequestsBatchable';
    public static final String BATCH_JOB_NAME = 'Xfleet Integration job';

    public static final String STATUS_SUCCESS = 'Success';
    public static final String STATUS_FAILED = 'Failed';

    public static final Set<String> JOB_IN_PROGRESS_STATUSES = new Set<String>{'Queued', 'Preparing', 'Processing'};

    @InvocableMethod(label='Xfleet Integration Job Run' description='Manually trigger Xfleet Integration Job run!')
    public static void runNavisionIntegrationJob() {
        scheduleIntegrationBatch(0);
    }

    public static Id scheduleIntegrationBatch() {
        Integer delay = getJobDelay();
        return scheduleIntegrationBatch(delay);
    }

    public static Id scheduleIntegrationBatch(Integer delay) {
        // are there any integration request to process?
        List<Integration_Request__c> irCheck = [SELECT id FROM Integration_Request__c WHERE Status__c = NULL LIMIT 1];
        if (irCheck.isEmpty()) {
            return null;
        }
        // is the job already scheduled?
        List<CronJobDetail> cronJobs = [SELECT Id, Name FROM CronJobDetail WHERE Name = :BATCH_JOB_NAME];
        if (cronJobs.size() > 0) {
            return cronJobs.get(0).Id;
        }
        // is the job already in progress?
        List<AsyncApexJob> alreadyScheduledJobs = [
            SELECT ApexClassId, CreatedDate, CronTriggerId, Id, JobType, MethodName, Status
            FROM AsyncApexJob
            WHERE Status = 'In Progress' AND JobType = 'BatchApex' AND ApexClass.Name = :BATCH_JOB_APEX_NAME
        ];
        if (alreadyScheduledJobs.size() > 0) {
            // already scheduled
            return alreadyScheduledJobs.get(0).Id;
        }
        // not already scheduled, schedule NEW
        IntegrationRequestsBatchable theBatch = new IntegrationRequestsBatchable();
        // TODO scope size
        return System.scheduleBatch(theBatch, BATCH_JOB_NAME, delay);
    }

    public static void updateIntegrationRequestsRollups() {
        // get all integration request since last job run to get impacted vehicles
        Datetime lastRun = getLastJobRunTime();
        Set<Id> vehicles4UpdateIds = new Set<Id>();
        for (Integration_Request__c req : [SELECT Vehicle__c FROM Integration_Request__c WHERE LastModifiedDate >= :lastRun]) {
            vehicles4UpdateIds.add(req.Vehicle__c);
        }
        // any vehicles for update?
        if (!vehicles4UpdateIds.isEmpty()) {
            List<Vehicle__c> vehicles4Update = new List<Vehicle__c>();
            // get the vehicles
            Map<Id, Vehicle__c> mVehicles = new Map<Id, Vehicle__c>();
            // clear the current counters, so we set the correct value later
            for (Vehicle__c veh : [
                SELECT id, Integration_Requests_Number_Success__c, Integration_Requests_Number_Failed__c, Integration_Requests_Number_Not_Run_Yet__c
                FROM Vehicle__c
                WHERE Id IN :vehicles4UpdateIds
            ]) {
                veh.Integration_Requests_Number_Failed__c = 0;
                veh.Integration_Requests_Number_Not_Run_Yet__c = 0;
                veh.Integration_Requests_Number_Success__c = 0;
                mVehicles.put(veh.Id, veh);
            }
            // get the aggregated roll-ups for Integration Requests on these vehicles
            AggregateResult[] groupedIntegrationResults = [
                SELECT Vehicle__c, Status__c, count(id)
                FROM Integration_Request__c
                WHERE Vehicle__c IN :vehicles4UpdateIds
                GROUP BY Vehicle__c, Status__c
            ];
            for (AggregateResult ar : groupedIntegrationResults) {
                Id vehicleId = (Id) ar.get('Vehicle__c');
                Vehicle__c veh = mVehicles.get(vehicleId);
                String status = (String) ar.get('Status__c');
                Integer count = (Integer) ar.get('expr0');
                if (status == null) {
                    veh.Integration_Requests_Number_Not_Run_Yet__c = count;
                } else if (status.endsWithIgnoreCase('Success')) {
                    veh.Integration_Requests_Number_Success__c = count;
                } else if (status.endsWithIgnoreCase('Failed')) {
                    veh.Integration_Requests_Number_Failed__c = count;
                }
                mVehicles.put(vehicleId, veh);
            }
            // update vehicles
            update mVehicles.values();
        }
    }

    public static Integer getJobDelay() {
        IntegrationSettings__c settings = IntegrationSettings__c.getInstance();
        return (Integer) settings.Batch_Job_Delay_in_minutes__c;
    }

    public static Datetime getLastJobRunTime() {
        IntegrationSettings__c settings = IntegrationSettings__c.getInstance();
        return settings.Job_last_run_at__c;
    }

    public static void setLastJobRunTime(Datetime runDatetime) {
        IntegrationSettings__c settings = IntegrationSettings__c.getOrgDefaults();
        settings.Job_last_run_at__c = runDatetime;
        update settings;
    }
}