force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>if needed specify data / request body</description>
    <inlineHelpText>if needed specify data / request body</inlineHelpText>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationRequestsAutoITVehicle.cls
public with sharing class IntegrationRequestsAutoITVehicle implements IntegrationRequestsProcess {
    public static final String METHOD_UPSERT = 'AutoIT-upsertCar';
    public static final String METHOD_STATUS_UPDATE = 'AutoIT-carStatusUpdate';

    public Integration_Request__c process(Integration_Request__c req, Vehicle__c veh) {
        AutoITVehicle autoItApi;
        // CREATE / UPDATE = UPSERT vehicle
        if (req.API_Method__c.equals(METHOD_UPSERT)) {
            autoItApi = new AutoITVehicleUpsert();
        } else if (req.API_Method__c.equals(METHOD_STATUS_UPDATE)) {
            // STATUS UPDATE
            // TODO status update
        }
        // is method supported?
        if (autoItApi != null) {
            // prepare data and call API
            AutoITVehicleObject theCar;
            // are data already prepared in the request record?
            if (String.isNotBlank(req.Data__c)) {
                theCar = (AutoITVehicleObject) JSON.deserialize(req.Data__c, AutoITVehicleObject.class);
            } else {
                // clone the vehicle to skip "SObject row was retrieved via SOQL without querying the requested field" error
                Vehicle__c tempVehicle = veh.clone();
                theCar = new AutoITVehicleObject(tempVehicle);
                req.Data__c = JSON.serialize(theCar, true);
            }
            HttpRequest apiReq = autoItApi.prepareRequest(theCar);
            HttpResponse apiResp = autoItApi.call(apiReq);
            // is it success?
            Integer statusCode = apiResp.getStatusCode();
            if ((statusCode == 200) || (statusCode == 201)) {
                // SUCCESS
                req.Status__c = IntegrationRequestsUtility.STATUS_SUCCESS;
            } else {
                req.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            }
            // add message
            req.Message__c = constructResponseMessage(apiResp);
        } else {
            req.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            req.Message__c = IntegrationRequestsBatchable.ERROR_WRONG_METHOD;
        }
        // return the updated req
        return req;
    }

    private String constructResponseMessage(HttpResponse httpResp) {
        String message = '[' + httpResp.getStatusCode() + ', ' + httpResp.getStatus() + ']';
        if (String.isNotBlank(httpResp.getBody())) {
            message += '\n' + httpResp.getBody();
        }
        return message;
    }
}