force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Last_Processing_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Processing_Time__c</fullName>
    <label>Last Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Batch_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Batch_Distribution__c</fullName>
    <label>Batch Distribution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Valutacar</fullName>
            </value>
            <value>
                <fullName>DK-car</fullName>
            </value>
            <value>
                <fullName>Mini-lease</fullName>
            </value>
            <value>
                <fullName>Full-tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_plate__c.field-meta.xml
<CustomField>
    <fullName>License_plate__c</fullName>
    <label>License plate</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NAVCarsIntegrationBatchable.cls
public with sharing class NAVCarsIntegrationBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public static final String METHOD_CREATE = 'NAV-createCar';
    public static final String METHOD_UPDATE = 'NAV-updateCar';
    public static final List<String> SUPPORTED_API_CALLS = new List<String>{ METHOD_CREATE, METHOD_UPDATE };
    public static final String STATUS_SUCCESS = 'Success';
    public static final String STATUS_FAILED = 'Failed';

    public static final String ERROR_NO_VEHICLE = 'Vehicle has not been assigned to the request!';
    public static final String ERROR_WRONG_METHOD = 'Method undefinied!';

    public NAVCarsIntegrationBatchable() {
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(
            [SELECT Status__c, Vehicle__c, API_Method__c FROM Integration_Request__c WHERE Status__c = NULL AND API_Method__c IN :SUPPORTED_API_CALLS]
        );
    }

    public void execute(Database.BatchableContext context, List<Integration_Request__c> scope) {
        Map<Id, Id> mVehicle2Request = new Map<Id, Id>();
        for (Integration_Request__c ir : scope) {
            if (ir.Vehicle__c != null) {
                mVehicle2Request.put(ir.Vehicle__c, ir.Id);
            }
        }
        // query vehicles data
        Map<Id, Vehicle__c> mVehicles = new Map<Id, Vehicle__c>(
            [SELECT vinNumber__c, License_plate__c, Batch_Distribution__c FROM Vehicle__c WHERE Id IN :mVehicle2Request.keySet()]
        );
        for (Integration_Request__c ir : scope) {
            // set Integration Request processed timestamp
            ir.Last_Processing_Time__c = System.now();
            if (ir.Vehicle__c != null) {
                // process API calls one-by-one
                ir = processSingleRequest(ir, mVehicles.get(ir.Vehicle__c));
            } else {
                // ERROR there is no vehicle assigned to the request
                ir.Status__c = STATUS_FAILED;
                ir.Message__c = ERROR_NO_VEHICLE;
            }
        }
        update scope;
    }

    public void finish(Database.BatchableContext context) {
    }

    private Integration_Request__c processSingleRequest(Integration_Request__c req, Vehicle__c veh) {
        NAVCars navApi;
        // CREATE
        if (req.API_Method__c.equals(METHOD_CREATE)) {
            navApi = new NAVCarsCreate();
        } else if (req.API_Method__c.equals(METHOD_UPDATE)) {
            // UPDATE
            navApi = new NAVCarsUpdate(veh.vinNumber__c);
        }
        // is method supported?
        if (navApi != null) {
            // prepare data and call API
            NAVCarsObject theCar = new NAVCarsObject(veh.vinNumber__c, veh.License_plate__c, veh.Batch_Distribution__c);
            HttpRequest navApiReq = navApi.prepareRequest(theCar);
            HttpResponse navApiResp = navApi.call(navApiReq);
            // is it success?
            Integer statusCode = navApiResp.getStatusCode();
            if ((statusCode == 200) || (statusCode == 201)) {
                // SUCCESS
                req.Status__c = STATUS_SUCCESS;
            } else {
                req.Status__c = STATUS_FAILED;
            }
            // add message
            req.Message__c = constructResponseMessage(navApiResp);
        } else {
            req.Status__c = STATUS_FAILED;
            req.Message__c = ERROR_WRONG_METHOD;
        }
        // return the updated req
        return req;
    }

    private String constructResponseMessage(HttpResponse httpResp) {
        String message = '[' + httpResp.getStatusCode() + ', ' + httpResp.getStatus() + ']';
        if (String.isNotBlank(httpResp.getBody())) {
            message += '\n' + httpResp.getBody();
        }
        return message;
    }
}