force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>if needed specify data / request body</description>
    <inlineHelpText>if needed specify data / request body</inlineHelpText>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Last_Processing_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Processing_Time__c</fullName>
    <label>Last Processing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Requests_Processor__mdt/Integration_Requests_Processor__mdt.object-meta.xml
<CustomObject>
    <description>define mapping between Integration Request API method and Apex processor class</description>
    <label>Integration Requests Processor</label>
    <pluralLabel>Integration Requests Processors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Requests_Processor__mdt/fields/Apex_Process__c.field-meta.xml
<CustomField>
    <fullName>Apex_Process__c</fullName>
    <description>Name of the apex class which implements IntegrationRequestsProcess interface to process the request of the API method</description>
    <inlineHelpText>Name of the apex class which implements IntegrationRequestsProcess interface to process the request of the API method</inlineHelpText>
    <label>Apex Process</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Requests_Processor__mdt/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
                <default>true</default>
                <label>NAV-createCar</label>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>AutoIT-carStatusUpdate</fullName>
            </value>
            <value>
                <fullName>AutoIT-updateCar</fullName>
            </value>
            <value>
                <fullName>AutoIT-createCar</fullName>
            </value>
            <value>
                <fullName>AutoIT-upsertCar</fullName>
                <isActive>false</isActive>
                <label>AutoIT-upsertCar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationRequestsBatchable.cls
public with sharing class IntegrationRequestsBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    public Map<String, String> SUPPORTED_API_CALLS;
    public Boolean isAnyFailedRequest = false;
    public Integer failedRequestCount = 0;

    public static final String ERROR_NO_VEHICLE = 'Vehicle has not been assigned to the request!';
    public static final String ERROR_WRONG_METHOD = 'Method undefinied!';

    public static final String VEHICLE_FIELDS = Label.Xfleet_Integration_Request_Vehicle_Fields;

    public IntegrationRequestsBatchable() {
        // get supported calls
        SUPPORTED_API_CALLS = new Map<String, String>();
        for (Integration_Requests_Processor__mdt irProcessorSetting : [SELECT API_Method__c, Apex_Process__c FROM Integration_Requests_Processor__mdt]) {
            SUPPORTED_API_CALLS.put(irProcessorSetting.API_Method__c, irProcessorSetting.Apex_Process__c);
        }
        System.debug(LoggingLevel.FINE, 'initialize integration job for these methods: ' + SUPPORTED_API_CALLS?.keySet());
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        System.debug(LoggingLevel.FINE, 'query integration requests for these methods: ' + SUPPORTED_API_CALLS?.keySet());
        return Database.getQueryLocator(
            [
                SELECT Status__c, Vehicle__c, API_Method__c, Data__c
                FROM Integration_Request__c
                WHERE Status__c = NULL AND API_Method__c IN :SUPPORTED_API_CALLS.keySet()
            ]
        );
    }

    public void execute(Database.BatchableContext context, List<Integration_Request__c> scope) {
        System.debug(LoggingLevel.DEBUG, 'execute integration requests: ' + scope);
        Map<Id, Id> mVehicle2Request = new Map<Id, Id>();
        for (Integration_Request__c ir : scope) {
            if (ir.Vehicle__c != null) {
                mVehicle2Request.put(ir.Vehicle__c, ir.Id);
            }
        }
        // query vehicles data
        String vehiclesQuery = 'SELECT ' + String.escapeSingleQuotes(VEHICLE_FIELDS) + ' FROM Vehicle__c WHERE Id IN :vehIds';
        Map<String, Object> vehiclesQueryParams = new Map<String, Object>{ 'vehIds' => mVehicle2Request.keySet() };
        Map<Id, Vehicle__c> mVehicles = new Map<Id, Vehicle__c>((List<Vehicle__c>)Database.queryWithBinds(vehiclesQuery, vehiclesQueryParams, AccessLevel.SYSTEM_MODE));
        System.debug(LoggingLevel.DEBUG, 'execute integration requests with these vehicles: ' + mVehicles);
        for (Integration_Request__c ir : scope) {
            // set Integration Request processed timestamp
            ir.Last_Processing_Time__c = System.now();
            if (ir.Vehicle__c != null) {
                // process API calls one-by-one
                ir = processSingleRequest(ir, mVehicles.get(ir.Vehicle__c));
            } else {
                // ERROR there is no vehicle assigned to the request
                ir.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
                ir.Message__c = ERROR_NO_VEHICLE;
            }
            if (ir.Status__c.equals(IntegrationRequestsUtility.STATUS_FAILED) && !isAnyFailedRequest) {
                isAnyFailedRequest = true;
                failedRequestCount++;
            }
        }
        update scope;
    }

    public void finish(Database.BatchableContext context) {
        // update count of integration request on a vehicle
        IntegrationRequestsUtility.updateIntegrationRequestsRollups();
        // any post actions?
        IntegrationRequestsUtility.postProcessActions();
        // set the timestamp when the job was finished
        IntegrationRequestsUtility.setLastJobRunTime(System.now());
        // any failed request?
        if (isAnyFailedRequest) {
            IntegrationRequestsUtility.notifyAdminsAboutFailedRequests(failedRequestCount);
        }
    }

    private Integration_Request__c processSingleRequest(Integration_Request__c req, Vehicle__c veh) {
        IntegrationRequestsProcess irProcess;
        if (SUPPORTED_API_CALLS.containsKey(req.API_Method__c)) {
            // Find the right implmenation of IR processor
            String apexProcessorType = SUPPORTED_API_CALLS.get(req.API_Method__c);
            // Get the Type corresponding to the class name
            Type t = Type.forName(apexProcessorType);
            // instantiate the process class
            irProcess = (IntegrationRequestsProcess) t.newInstance();
            // process the Integration Request
            req = irProcess.process(req, veh);
        } else {
            // FAILED - method not supported
            req.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            req.Message__c = ERROR_WRONG_METHOD;
        }
        return req;
    }
}