force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>setting for using Integration Requests</description>
    <label>Xfleet Integration</label>
</CustomObject>

force-app/main/default/objects/IntegrationSettings__c/fields/Batch_Job_Delay_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Delay_in_minutes__c</fullName>
    <defaultValue>3</defaultValue>
    <description>integration job is scheduled to run after X minutes after &quot;trigger&quot;</description>
    <inlineHelpText>integration job is scheduled to run after X minutes after &quot;trigger&quot;</inlineHelpText>
    <label>Batch Job Delay (in minutes)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>How many Integration Request are processed in one batch run. Choose lower number if you have issue with timeout or limits.</description>
    <inlineHelpText>How many Integration Request are processed in one batch run. Choose lower number if you have issue with timeout or limits.</inlineHelpText>
    <label>Batch Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegrationSettings__c/fields/Job_last_run_at__c.field-meta.xml
<CustomField>
    <fullName>Job_last_run_at__c</fullName>
    <description>When the Integration Requests have been last processed.</description>
    <inlineHelpText>When the Integration Requests have been last processed.</inlineHelpText>
    <label>Job last run at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Integration_Requests_Number_Failed__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requests_Number_Failed__c</fullName>
    <description>System rollup field that display number of Integration Request related to the vehicle and processed with ERROR.</description>
    <inlineHelpText>System rollup field that display number of Integration Request related to the vehicle and processed with ERROR.</inlineHelpText>
    <label>Integration Requests Number - Failed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Integration_Requests_Number_Not_Run_Yet__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requests_Number_Not_Run_Yet__c</fullName>
    <description>System rollup field that display number of Integration Request related to the vehicle and that have not been processed yet.</description>
    <inlineHelpText>System rollup field that display number of Integration Request related to the vehicle and that have not been processed yet.</inlineHelpText>
    <label>Integration Requests Number -Not Run Yet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Integration_Requests_Number_Success__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requests_Number_Success__c</fullName>
    <description>System rollup field that display number of Integration Request related to the vehicle and processed successfully.</description>
    <inlineHelpText>System rollup field that display number of Integration Request related to the vehicle and processed successfully.</inlineHelpText>
    <label>Integration Requests Number - Success</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationRequestsUtility_Test.cls
@isTest
public class IntegrationRequestsUtility_Test {
    private static final Integer BATCH_DELAY = 5;
    private static final Integer BATCH_SIZE = 15;
    private static final Datetime LAST_JOB_RUN = Datetime.newInstance(2022, 11, 28, 5, 30, 0);

    @TestSetup
    static void makeData() {
        IntegrationSettings__c testSettings = new IntegrationSettings__c();
        testSettings.Batch_Job_Delay_in_minutes__c = BATCH_DELAY;
        testSettings.Job_last_run_at__c = LAST_JOB_RUN;
        testSettings.Batch_Size__c = BATCH_SIZE;
        insert testSettings;
    }

    @isTest
    public static void settingsTests() {
        Integer delay = IntegrationRequestsUtility.getJobDelay();
        System.assertEquals(BATCH_DELAY, delay, 'Batch job delay settings not read properly!');

        Integer size = IntegrationRequestsUtility.getBatchSize();
        System.assertEquals(BATCH_SIZE, size, 'Batch Size settings not read properly!');

        Datetime lastRun = IntegrationRequestsUtility.getLastJobRunTime();
        System.assertEquals(LAST_JOB_RUN, lastRun, 'Last job run time settings not read properly!');

        IntegrationRequestsUtility.setLastJobRunTime(System.now());
    }

    @isTest
    public static void scheduleJobTests() {
        // Xfleet dependency on Vehicle__c
        Map<String, Object> vehParams = new Map<String, Object>{ 'vinNumber__c' => 'VINUNIT78364' };
        Vehicle__c testVehicle = TestUtilitySIXT.createVehicle(TestUtilitySIXT.createBatch().Id, vehParams);
        Integration_Request__c irTest = new Integration_Request__c();
        irTest.API_Method__c = 'UnitTest';
        irTest.Vehicle__c = testVehicle.Id;
        insert irTest;
        Test.startTest();
        Id jobId = IntegrationRequestsUtility.scheduleIntegrationBatch();
        Id jobId2nd = IntegrationRequestsUtility.scheduleIntegrationBatch();
        IntegrationRequestsUtility.runNavisionIntegrationJob();
        Test.stopTest();
        System.assert(jobId != null, 'Job has not been scheduled!');
        System.assertEquals(jobId, jobId2nd, '2nd job should not been scheduled and same Id shall be returned!');
    }

    @isTest
    public static void errorNotificationTests() {
        IntegrationRequestsUtility.notifyAdminsAboutFailedRequests(4);
        IntegrationRequestsUtility.notifyAdminsAboutFailedRequests(null);
    }

    @isTest
    public static void rollupsTests() {
        // Xfleet dependency on Vehicle__c
        Map<String, Object> vehParams = new Map<String, Object>{ 'vinNumber__c' => 'VINUNIT78364' };
        Vehicle__c testVehicle = TestUtilitySIXT.createVehicle(TestUtilitySIXT.createBatch().Id, vehParams);

        // prepare integration request for rollups
        Integer notProcessedCount = 4;
        Integer successCount = 13;
        Integer failedCount = 2;

        List<Integration_Request__c> irsTest = new List<Integration_Request__c>();
        // not processed IRs
        for (Integer i = 0; i < notProcessedCount; i++) {
            Integration_Request__c irTest = new Integration_Request__c();
            irTest.API_Method__c = 'UnitTest';
            irTest.Vehicle__c = testVehicle.Id;
            irsTest.add(irTest);
        }
        // successfully processed
        for (Integer i = 0; i < successCount; i++) {
            Integration_Request__c irTest = new Integration_Request__c();
            irTest.API_Method__c = 'UnitTest';
            irTest.Vehicle__c = testVehicle.Id;
            irTest.Status__c = IntegrationRequestsUtility.STATUS_SUCCESS;
            irsTest.add(irTest);
        }
        // failed processed
        for (Integer i = 0; i < failedCount; i++) {
            Integration_Request__c irTest = new Integration_Request__c();
            irTest.API_Method__c = 'UnitTest';
            irTest.Vehicle__c = testVehicle.Id;
            irTest.Status__c = IntegrationRequestsUtility.STATUS_FAILED;
            irsTest.add(irTest);
        }
        insert irsTest;

        Test.startTest();
        IntegrationRequestsUtility.updateIntegrationRequestsRollups();
        Test.stopTest();

        testVehicle = [
            SELECT id, Integration_Requests_Number_Success__c, Integration_Requests_Number_Failed__c, Integration_Requests_Number_Not_Run_Yet__c
            FROM Vehicle__c
            WHERE Id = :testVehicle.Id
        ];

        // asserts
        System.assertEquals(notProcessedCount, testVehicle.Integration_Requests_Number_Not_Run_Yet__c, 'Not processed requests rollup failed!');
        System.assertEquals(successCount, testVehicle.Integration_Requests_Number_Success__c, 'Successfull requests rollup failed!');
        System.assertEquals(failedCount, testVehicle.Integration_Requests_Number_Failed__c, 'Failed requests rollup failed!');
    }
}