force-app/main/default/objects/Integration_Request__c/Integration_Request__c.object-meta.xml
<CustomObject>
    <label>Integration Request</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>Integration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Request__c/fields/API_Method__c.field-meta.xml
<CustomField>
    <fullName>API_Method__c</fullName>
    <label>API Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAV-createCar</fullName>
            </value>
            <value>
                <fullName>NAV-updateCar</fullName>
            </value>
            <value>
                <fullName>NAV-createInvoiceQuote</fullName>
            </value>
            <value>
                <fullName>UnitTest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed - reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Integration Requests</relationshipLabel>
    <relationshipName>Integration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/AutoDesktop_Id__c.field-meta.xml
<CustomField>
    <fullName>AutoDesktop_Id__c</fullName>
    <description>vehicle ID in AutoDesktop</description>
    <inlineHelpText>vehicle ID in AutoDesktop</inlineHelpText>
    <label>AutoDesktop Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/License_plate__c.field-meta.xml
<CustomField>
    <fullName>License_plate__c</fullName>
    <label>License plate</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vinNumber__c.field-meta.xml
<CustomField>
    <fullName>vinNumber__c</fullName>
    <label>VIN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationRequestsAutoITVehicle_Test.cls
@isTest
public class IntegrationRequestsAutoITVehicle_Test {
    public static final String TEST_VIN = 'VINUNIT78364';
    public static final String TEST_REG_NUM = 'RN 12345';
    public static final String TEST_VEHICLE_AUTODESKTOP_ID = '4987912345';

    private final static String MOCK_OK = 'AutoITVehicles_BasicResponse';

    private final static String VEHICLE_QUERY = 'SELECT ' + Label.Xfleet_Integration_Request_Vehicle_Fields + ' FROM Vehicle__c WHERE vinNumber__c = :TEST_VIN';

    @TestSetup
    static void makeData() {
        // Xfleet dependency on Vehicle__c
        Map<String, Object> vehParams = new Map<String, Object>{ 'vinNumber__c' => TEST_VIN, 'license_plate__c' => TEST_REG_NUM };
        Vehicle__c testVehicle = TestUtilitySIXT.createVehicle(TestUtilitySIXT.createBatch().Id, vehParams);
    }

    @isTest
    public static void createMethodTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_OK);
        mock.setStatusCode(201);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = (Vehicle__c) Database.query(VEHICLE_QUERY);
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsAutoITVehicle.METHOD_INSERT;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsAutoITVehicle testProcessor = new IntegrationRequestsAutoITVehicle();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void updateMethodTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_OK);
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = (Vehicle__c) Database.query(VEHICLE_QUERY);
        veh.AutoDesktop_Id__c = TEST_VEHICLE_AUTODESKTOP_ID;
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsAutoITVehicle.METHOD_UPDATE;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsAutoITVehicle testProcessor = new IntegrationRequestsAutoITVehicle();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void markAsSoldTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_OK);
        mock.setStatusCode(204);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = (Vehicle__c) Database.query(VEHICLE_QUERY);
        veh.AutoDesktop_Id__c = TEST_VEHICLE_AUTODESKTOP_ID;
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsAutoITVehicle.METHOD_STATUS_UPDATE;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsAutoITVehicle testProcessor = new IntegrationRequestsAutoITVehicle();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }

    @isTest
    public static void deleteTest() {
        // Use StaticResourceCalloutMock built-in class to set mock response
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource(MOCK_OK);
        mock.setStatusCode(204);
        mock.setHeader('Content-Type', 'application/json');

        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);

        Vehicle__c veh = (Vehicle__c) Database.query(VEHICLE_QUERY);
        veh.AutoDesktop_Id__c = TEST_VEHICLE_AUTODESKTOP_ID;
        Integration_Request__c ir = new Integration_Request__c();
        ir.API_Method__c = IntegrationRequestsAutoITVehicle.METHOD_DELETE;
        ir.Vehicle__c = veh.Id;
        IntegrationRequestsAutoITVehicle testProcessor = new IntegrationRequestsAutoITVehicle();
        Test.startTest();
        ir = testProcessor.process(ir, veh);
        Test.stopTest();
        System.assertEquals(IntegrationRequestsUtility.STATUS_SUCCESS, ir.Status__c, 'Wrong status set!');
    }
}