force-app/main/default/objects/Fleet_Forecast__c/Fleet_Forecast__c.object-meta.xml
<CustomObject>
    <description>Single row of fleet forecast</description>
    <label>Fleet Forecast</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Fleet Forecast Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Forecast__c/fields/Current_fleet_DK__c.field-meta.xml
<CustomField>
    <fullName>Current_fleet_DK__c</fullName>
    <description>Number of DK vehicles of this car group in the fleet at the period beginning</description>
    <inlineHelpText>Number of DK vehicles of this car group in the fleet at the period beginning</inlineHelpText>
    <label>Current fleet - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Current_fleet_Valuta__c.field-meta.xml
<CustomField>
    <fullName>Current_fleet_Valuta__c</fullName>
    <description>Number of valuta vehicles of this car group in the fleet at the period beginning</description>
    <inlineHelpText>Number of valuta vehicles of this car group in the fleet at the period beginning</inlineHelpText>
    <label>Current fleet - Valuta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Defleet_DK__c.field-meta.xml
<CustomField>
    <fullName>Defleet_DK__c</fullName>
    <description>Number of DK vehicles of the car group planned to be defleeted this period</description>
    <inlineHelpText>Number of DK vehicles of the car group planned to be defleeted this period</inlineHelpText>
    <label>Defleet - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Defleet_Valuta__c.field-meta.xml
<CustomField>
    <fullName>Defleet_Valuta__c</fullName>
    <description>Number of valuta vehicles of the car group planned to be defleeted this period</description>
    <inlineHelpText>Number of valuta vehicles of the car group planned to be defleeted this period</inlineHelpText>
    <label>Defleet - Valuta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/First_Day__c.field-meta.xml
<CustomField>
    <fullName>First_Day__c</fullName>
    <description>first day of this forecasting period</description>
    <inlineHelpText>first day of this forecasting period</inlineHelpText>
    <label>First Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Infleet_DK__c.field-meta.xml
<CustomField>
    <fullName>Infleet_DK__c</fullName>
    <description>Number of DK vehicles of the car group planned to be infleeted this period</description>
    <inlineHelpText>Number of DK vehicles of the car group planned to be infleeted this period</inlineHelpText>
    <label>Infleet - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Infleet_Valuta__c.field-meta.xml
<CustomField>
    <fullName>Infleet_Valuta__c</fullName>
    <description>Number of valuta vehicles of the car group planned to be infleeted this period</description>
    <inlineHelpText>Number of valuta vehicles of the car group planned to be infleeted this period</inlineHelpText>
    <label>Infleet - Valuta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Last_Day__c.field-meta.xml
<CustomField>
    <fullName>Last_Day__c</fullName>
    <description>last day of this forecasting period</description>
    <inlineHelpText>last day of this forecasting period</inlineHelpText>
    <label>Last Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>only one forecast per year/month/vehicle group shall be Actual</description>
    <inlineHelpText>only one forecast per year/month/vehicle group shall be Actual</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Actual</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Group of vehicles in this forecast category</description>
    <inlineHelpText>Group of vehicles in this forecast category</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Fleet Forecasts</relationshipLabel>
    <relationshipName>Fleet_Forecasts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Expected_Defleet_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Defleet_Date__c</fullName>
    <description>When is the car expected to be defleeted?</description>
    <inlineHelpText>When is the car expected to be defleeted?</inlineHelpText>
    <label>Expected Defleet Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Planned_Infleet_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Infleet_Date__c</fullName>
    <label>Planned Infleet Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Procurement</fullName>
                <default>true</default>
                <label>Procurement</label>
            </value>
            <value>
                <fullName>Infleet</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Defleet</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Stock Car</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Valuta_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Valuta_Vehicle__c</fullName>
    <description>true if the vehicle is &quot;valuta car&quot;</description>
    <formula>IF(ISPICKVAL(Batch_Distribution__c, &quot;Valutacar&quot;), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>true if the vehicle is &quot;valuta car&quot;</inlineHelpText>
    <label>Valuta Vehicle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Batch__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Batch__c</fullName>
    <label>Vehicle Batch</label>
    <referenceTo>vehicleBatch__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>car group, automatically set from acriss code</description>
    <inlineHelpText>car group, automatically set from acriss code</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_status__c</fullName>
    <description>status of the vehicle in COBRA</description>
    <inlineHelpText>status of the vehicle in COBRA</inlineHelpText>
    <label>Vehicle status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - Car is rented</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Car is ready for rental</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 - Default</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 - Car is not ready, block for a reservation</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 - Car is available, but not cleaned</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 - Car is not available, blocked for workshop etc.</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6 - Car is on workshop</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10 - Car arrived, but not checked in yet</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Car is checked in, but rental agreement not closed</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 - Car is blocked for sale</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50 - Car is on station, but not on contract</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>99 - Car is on checkout</label>
            </value>
            <value>
                <fullName>00-</fullName>
                <label>00- - Car is defleeted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No deal</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
                <default>true</default>
                <label>Offer</label>
            </value>
            <value>
                <fullName>Deal - Waiting for details</fullName>
            </value>
            <value>
                <fullName>Deal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NO LONGER REQUIRED as batch can include several groups
we are buying vehicles for this Vehicle Group</description>
    <inlineHelpText>we are buying vehicles for this Vehicle Group</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Vehicle Batches</relationshipLabel>
    <relationshipName>Vehicle_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FleetForecastUpdateUtility.cls
public with sharing class FleetForecastUpdateUtility {
    // calculate updates for all fleet forecast for one group of vehicles
    public static List<Fleet_Forecast__c> getFleetForecastUpdates(Id vehicleGroupId) {
        System.debug('getting fleet forecast for group: ' + vehicleGroupId);
        // get all fleet forecast that are not in the past or archived
        List<Fleet_Forecast__c> forecasts = [
            SELECT
                Vehicle_Group__c,
                First_Day__c,
                Last_Day__c,
                Current_fleet_DK__c,
                Infleet_DK__c,
                Defleet_DK__c,
                Current_fleet_Valuta__c,
                Infleet_Valuta__c,
                Defleet_Valuta__c
            FROM Fleet_Forecast__c
            WHERE Status__c != 'Archived' AND Last_Day__c > :Date.today() AND Vehicle_Group__c = :vehicleGroupId
        ];
        // get all active or infleet cars for the vehicle group
        List<Vehicle__c> vehicles = [
            SELECT Id, Planned_Infleet_Date__c, Expected_Defleet_Date__c, Registration_Date__c, Valuta_Vehicle__c
            FROM Vehicle__c
            WHERE
                (Vehicle_Group__c = :vehicleGroupId
                OR (Vehicle_Group__c = NULL
                AND Vehicle_Batch__r.Vehicle_Group__c = :vehicleGroupId))
                AND Vehicle_Status__c != 99
            ORDER BY Expected_Defleet_Date__c ASC NULLS FIRST
        ];
        // calculate updates for each period
        List<Fleet_Forecast__c> forecastsUpdated = new List<Fleet_Forecast__c>();
        for (Fleet_Forecast__c singleForecast : forecasts) {
            Fleet_Forecast__c singleForecastUpdated = updateFleetForecast(singleForecast, vehicles);
            // update only if there are changes
            if (singleForecastUpdated != null) {
                forecastsUpdated.add(singleForecastUpdated);
            }
        }
        // TODO - remove
        for (Fleet_Forecast__c ff : forecastsUpdated) {
            System.debug('forecast period (updated): ' + ff);
        }
        return forecastsUpdated;
    }

    public static Fleet_Forecast__c updateFleetForecast(Fleet_Forecast__c singlePeriod, List<Vehicle__c> vehicles) {
        System.debug(LoggingLevel.DEBUG, 'forecast period (before): ' + singlePeriod);
        System.debug(LoggingLevel.DEBUG, 'number of vehicles: ' + vehicles?.size());
        System.debug(LoggingLevel.FINE, 'vehicles: ' + vehicles);
        Integer numberActiveDK = 0;
        Integer numberInfleetDK = 0;
        Integer numberDefleetDK = 0;
        Integer numberActiveValuta = 0;
        Integer numberInfleetValuta = 0;
        Integer numberDefleetValuta = 0;
        // go through the list of vehicles
        for (Vehicle__c vehicle : vehicles) {
            // is the car DK or Valuta??
            // vehicle.Valuta_Vehicle__c

            // infleet - would be this vehicle infleeted in this period
            if (
                vehicle.Planned_Infleet_Date__c != null &&
                vehicle.Planned_Infleet_Date__c >= singlePeriod.First_Day__c &&
                vehicle.Planned_Infleet_Date__c <= singlePeriod.Last_Day__c
            ) {
                if (vehicle.Valuta_Vehicle__c) {
                    numberInfleetValuta++;
                } else {
                    numberInfleetDK++;
                }
            }
            // defleet - would be this vehicle defleeted in this period
            if (
                vehicle.Expected_Defleet_Date__c != null &&
                vehicle.Expected_Defleet_Date__c >= singlePeriod.First_Day__c &&
                vehicle.Expected_Defleet_Date__c <= singlePeriod.Last_Day__c
            ) {
                if (vehicle.Valuta_Vehicle__c) {
                    numberDefleetValuta++;
                } else {
                    numberDefleetDK++;
                }
            }
            // active - it is active at the period first day? OR would it be infleeted before period first day AND would NOT be defleeted before period first day
            // was it registered before the period start? Else is it planned to be infleeted before the period first day?
            Boolean isActive = false;
            if (vehicle.Registration_Date__c != null && vehicle.Registration_Date__c < singlePeriod.First_Day__c) {
                isActive = true;
            } else if (vehicle.Planned_Infleet_Date__c != null && vehicle.Planned_Infleet_Date__c < singlePeriod.First_Day__c) {
                isActive = true;
            }
            // is it planned to be defleeted before the period first day?
            if (vehicle.Expected_Defleet_Date__c != null && vehicle.Expected_Defleet_Date__c < singlePeriod.First_Day__c) {
                isActive = false;
            }
            // increase the count if is active before the first day
            if (isActive) {
                if (vehicle.Valuta_Vehicle__c) {
                    numberActiveValuta++;
                } else {
                    numberActiveDK++;
                }
            }
        }
        // any updates needed
        if (
            singlePeriod.Current_fleet_DK__c != numberActiveDK ||
            singlePeriod.Infleet_DK__c != numberInfleetDK ||
            singlePeriod.Defleet_DK__c != numberDefleetDK ||
            singlePeriod.Current_fleet_Valuta__c != numberActiveValuta ||
            singlePeriod.Infleet_Valuta__c != numberInfleetValuta ||
            singlePeriod.Defleet_Valuta__c != numberDefleetValuta
        ) {
            // update required
            singlePeriod.Current_fleet_DK__c = numberActiveDK;
            singlePeriod.Infleet_DK__c = numberInfleetDK;
            singlePeriod.Defleet_DK__c = numberDefleetDK;
            singlePeriod.Current_fleet_Valuta__c = numberActiveValuta;
            singlePeriod.Infleet_Valuta__c = numberInfleetValuta;
            singlePeriod.Defleet_Valuta__c = numberDefleetValuta;
        } else {
            // update not required - return null
            return null;
        }

        return singlePeriod;
    }
}