force-app/main/default/objects/Fleet_Forecast__c/Fleet_Forecast__c.object-meta.xml
<CustomObject>
    <description>Single row of fleet forecast</description>
    <label>Fleet Forecast</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Fleet Forecast Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Forecast__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Group of vehicles in this forecast category</description>
    <inlineHelpText>Group of vehicles in this forecast category</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Fleet Forecasts</relationshipLabel>
    <relationshipName>Fleet_Forecasts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FleetForecastUpdateBatch.cls
// list all vehicle groups and trigger Fleet Forecast update calculation 1 by 1
global class FleetForecastUpdateBatch implements Database.Batchable<Vehicle_Group__c> {
    global List<Vehicle_Group__c> start(Database.BatchableContext jobId) {
        List<Vehicle_Group__c> recordList = new List<Vehicle_Group__c>();
        // all vehicle groups
        recordList = [SELECT Id, Name FROM Vehicle_Group__c];
        return recordList;
    }

    global void execute(Database.BatchableContext jobId, List<Vehicle_Group__c> recordList) {
        // list of vehicles to update
        List<Fleet_Forecast__c> forecastsToUpdateAll = new List<Fleet_Forecast__c>();
        // go through list of vehicle groups and calculate updates for forecast for each group
        for (Vehicle_Group__c vehicleGroup : recordList) {
            // run utility method
            System.debug(LoggingLevel.DEBUG, 'calculate forecasts for vehicle group: ' + vehicleGroup);
            List<Fleet_Forecast__c> forecastsForTheGroup = FleetForecastUpdateUtility.getFleetForecastUpdates(vehicleGroup.Id);
            forecastsToUpdateAll.addAll(forecastsForTheGroup);
        }
        // any update?
        if (!forecastsToUpdateAll.isEmpty()) {
            update forecastsToUpdateAll;
        }
    }

    global void finish(Database.BatchableContext jobIdParam) {
    }
}