force-app/main/default/objects/Fleet_Forecast__c/Fleet_Forecast__c.object-meta.xml
<CustomObject>
    <description>Single row of fleet forecast</description>
    <label>Fleet Forecast</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Fleet Forecast Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Forecast__c/fields/Current_fleet_DK__c.field-meta.xml
<CustomField>
    <fullName>Current_fleet_DK__c</fullName>
    <description>Number of DK vehicles of this car group in the fleet at the period beginning</description>
    <inlineHelpText>Number of DK vehicles of this car group in the fleet at the period beginning</inlineHelpText>
    <label>Current fleet - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Defleet_DK__c.field-meta.xml
<CustomField>
    <fullName>Defleet_DK__c</fullName>
    <description>Number of DK vehicles of the car group planned to be defleeted this period</description>
    <inlineHelpText>Number of DK vehicles of the car group planned to be defleeted this period</inlineHelpText>
    <label>Defleet - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Infleet_DK__c.field-meta.xml
<CustomField>
    <fullName>Infleet_DK__c</fullName>
    <description>Number of DK vehicles of the car group planned to be infleeted this period</description>
    <inlineHelpText>Number of DK vehicles of the car group planned to be infleeted this period</inlineHelpText>
    <label>Infleet - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Long_Term_DK__c.field-meta.xml
<CustomField>
    <fullName>Long_Term_DK__c</fullName>
    <description>How many DK vehicles of that car group we would like to have in long term in this period</description>
    <inlineHelpText>How many DK vehicles of that car group we would like to have in long term in this period</inlineHelpText>
    <label>Long Term - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Long_Term_Valuta__c.field-meta.xml
<CustomField>
    <fullName>Long_Term_Valuta__c</fullName>
    <description>How many valuta vehicles of that car group we would like to have in long term in this period</description>
    <inlineHelpText>How many valuta vehicles of that car group we would like to have in long term in this period</inlineHelpText>
    <label>Long Term - Valuta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Short_Term_DK__c.field-meta.xml
<CustomField>
    <fullName>Short_Term_DK__c</fullName>
    <description>How many DK vehicles of that car group we would like to have in short term in this period</description>
    <inlineHelpText>How many DK vehicles of that car group we would like to have in short term in this period</inlineHelpText>
    <label>Short Term - DK</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Short_Term_Valuta__c.field-meta.xml
<CustomField>
    <fullName>Short_Term_Valuta__c</fullName>
    <description>How many valuta vehicles of that car group we would like to have in short term in this period</description>
    <inlineHelpText>How many valuta vehicles of that car group we would like to have in short term in this period</inlineHelpText>
    <label>Short Term - Valuta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Group of vehicles in this forecast category</description>
    <inlineHelpText>Group of vehicles in this forecast category</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Fleet Forecasts</relationshipLabel>
    <relationshipName>Fleet_Forecasts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NO LONGER REQUIRED as batch can include several groups
we are buying vehicles for this Vehicle Group</description>
    <inlineHelpText>we are buying vehicles for this Vehicle Group</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Vehicle Batches</relationshipLabel>
    <relationshipName>Vehicle_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FleetForecastUpdate_Test.cls
/* test class to test all classes related to FleetForecastUpdate:
 * - FleetForecastUpdateUtility
 * - FleetForecastUpdateBatch
 */
@isTest
public with sharing class FleetForecastUpdate_Test {
    @TestSetup
    static void makeData() {
        VehicleBatch__c testBatch = TestUtilitySIXT.createBatch();
        Vehicle_Group__c vg = [SELECT Id FROM Vehicle_Group__c]; //  there is just one vehicle group
        Map<String, Object> vehicleParams = new Map<String, Object>{
            'Acriss_code__c' => TestUtilitySIXT.ACCRIS_CODE,
            'Planned_Infleet_Date__c' => Date.today().addMonths(1),
            'Vehicle_Group__c' => vg.Id
        };
        TestUtilitySIXT.createVehicle(testBatch.Id, vehicleParams);
    }

    @isTest
    public static void fleetForecastBatch() {
        // test data
        // Fleet forecast - next month
        Vehicle_Group__c vg = [SELECT Id FROM Vehicle_Group__c];
        Date firstDayNextMonth = Date.today().addMonths(1).toStartOfMonth();
        Date lastDayNextMonth = Date.today().addMonths(2).toStartOfMonth().addDays(-1);
        Map<String, Object> ffParams = new Map<String, Object>{
            'Short_Term_DK__c' => 5,
            'Long_Term_DK__c' => 0,
            'Short_Term_Valuta__c' => 0,
            'Long_Term_Valuta__c' => 1
        };
        TestUtilitySIXT.createFleetForecast(vg.Id, firstDayNextMonth, lastDayNextMonth, ffParams);
        Test.startTest();
        Id batchJobId = Database.executeBatch(new FleetForecastUpdateBatch(), 200);
        Test.stopTest();
        Fleet_Forecast__c ffResult = [SELECT Infleet_DK__c, Defleet_DK__c, Current_fleet_DK__c FROM Fleet_Forecast__c LIMIT 1];
        System.assertEquals(1, ffResult.Infleet_DK__c, 'One vehicle shall be infleeted in the period!');
        System.assertEquals(0, ffResult.Current_fleet_DK__c, 'No vehicle at the period start is expected!');
    }
}