force-app/main/default/objects/Fleet_Forecast__c/Fleet_Forecast__c.object-meta.xml
<CustomObject>
    <description>Single row of fleet forecast</description>
    <label>Fleet Forecast</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Fleet Forecast Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet_Forecast__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <formula>TEXT(Year__c) + &quot;-&quot; + TEXT(Month__c) + &quot;-&quot; + Vehicle_Group__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/First_Day__c.field-meta.xml
<CustomField>
    <fullName>First_Day__c</fullName>
    <description>first day of this forecasting period</description>
    <inlineHelpText>first day of this forecasting period</inlineHelpText>
    <label>First Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Last_Day__c.field-meta.xml
<CustomField>
    <fullName>Last_Day__c</fullName>
    <description>last day of this forecasting period</description>
    <inlineHelpText>last day of this forecasting period</inlineHelpText>
    <label>Last Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Group of vehicles in this forecast category</description>
    <inlineHelpText>Group of vehicles in this forecast category</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Fleet Forecasts</relationshipLabel>
    <relationshipName>Fleet_Forecasts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fleet_Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceAndDamageCost__c/ServiceAndDamageCost__c.object-meta.xml
<CustomObject>
    <description>approximately costs for service, tyres and damage used in holding cost calculation</description>
    <label>Service and Damage Cost</label>
    <nameField>
        <displayFormat>SDC-{00000}</displayFormat>
        <label>Service and Damage Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service and Damage Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceAndDamageCost__c/fields/Damage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Damage_Cost__c</fullName>
    <description>damage cost per month</description>
    <inlineHelpText>damage cost per month</inlineHelpText>
    <label>Damage Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceAndDamageCost__c/fields/Period_Month__c.field-meta.xml
<CustomField>
    <fullName>Period_Month__c</fullName>
    <description>month number in the period</description>
    <inlineHelpText>month number in the period</inlineHelpText>
    <label>Period Month</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceAndDamageCost__c/fields/Service_and_Damage_Group__c.field-meta.xml
<CustomField>
    <fullName>Service_and_Damage_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service and Damage Group</label>
    <referenceTo>Service_and_Damage_Group__c</referenceTo>
    <relationshipLabel>Service and Damage Costs</relationshipLabel>
    <relationshipName>Service_and_Damage_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAndDamageCost__c/fields/Tyres_Service_Cost__c.field-meta.xml
<CustomField>
    <fullName>Tyres_Service_Cost__c</fullName>
    <description>cost for tyres and service per month</description>
    <inlineHelpText>cost for tyres and service per month</inlineHelpText>
    <label>Tyres &amp; Service Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TaxCalculation__c/TaxCalculation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>setting for tax calculation</description>
    <label>Tax Calculation</label>
</CustomObject>

force-app/main/default/objects/TaxCalculation__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>actual interest rate from tax agency</description>
    <inlineHelpText>actual interest rate from tax agency</inlineHelpText>
    <label>Interest Rate</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TaxCalculation__c/fields/Period_1_Length__c.field-meta.xml
<CustomField>
    <fullName>Period_1_Length__c</fullName>
    <defaultValue>3</defaultValue>
    <description>length of the 1st period for assumed value loss calculation in months</description>
    <inlineHelpText>length of the 1st period for assumed value loss calculation in months</inlineHelpText>
    <label>Period 1 Length</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaxCalculation__c/fields/Period_1_Rate__c.field-meta.xml
<CustomField>
    <fullName>Period_1_Rate__c</fullName>
    <defaultValue>2</defaultValue>
    <description>how much percent of value is lost per month during the 1st period</description>
    <inlineHelpText>how much percent of value is lost per month during the 1st period</inlineHelpText>
    <label>Period 1 Rate</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TaxCalculation__c/fields/Period_2_Length__c.field-meta.xml
<CustomField>
    <fullName>Period_2_Length__c</fullName>
    <defaultValue>33</defaultValue>
    <description>length of the 2nd period for assumed value loss calculation in months</description>
    <inlineHelpText>length of the 2nd period for assumed value loss calculation in months</inlineHelpText>
    <label>Period 2 Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaxCalculation__c/fields/Period_2_Rate__c.field-meta.xml
<CustomField>
    <fullName>Period_2_Rate__c</fullName>
    <defaultValue>1</defaultValue>
    <description>how much percent of value is lost per month during the 1st period</description>
    <inlineHelpText>how much percent of value is lost per month during the 1st period</inlineHelpText>
    <label>Period 2 Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>car group, automatically set from acriss code</description>
    <inlineHelpText>car group, automatically set from acriss code</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/Vehicle_Group__c.object-meta.xml
<CustomObject>
    <description>grouping of vehicles by acriss codes</description>
    <label>Vehicle Group</label>
    <nameField>
        <label>Vehicle Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Group__c/fields/Codes__c.field-meta.xml
<CustomField>
    <fullName>Codes__c</fullName>
    <description>acriss codes that are part of this group</description>
    <inlineHelpText>acriss codes that are part of this group</inlineHelpText>
    <label>Codes</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Acriss_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Group__c/fields/Service_and_Damage_Group__c.field-meta.xml
<CustomField>
    <fullName>Service_and_Damage_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>used to calculate cost for damage and service for vehicles from this vehicle group</description>
    <inlineHelpText>used to calculate cost for damage and service for vehicles from this vehicle group</inlineHelpText>
    <label>Service and Damage Group</label>
    <referenceTo>Service_and_Damage_Group__c</referenceTo>
    <relationshipLabel>Vehicle Groups</relationshipLabel>
    <relationshipName>Vehicle_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/vehicleBatch__c.object-meta.xml
<CustomObject>
    <label>Vehicle Batch</label>
    <nameField>
        <displayFormat>{YYYY}-B-{0000}</displayFormat>
        <label>Vehicle Batch ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/vehicleBatch__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>describe the reason for the batch</description>
    <inlineHelpText>describe the reason for the batch</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/vehicleBatch__c/fields/Vehicle_Group__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NO LONGER REQUIRED as batch can include several groups
we are buying vehicles for this Vehicle Group</description>
    <inlineHelpText>we are buying vehicles for this Vehicle Group</inlineHelpText>
    <label>Vehicle Group</label>
    <referenceTo>Vehicle_Group__c</referenceTo>
    <relationshipLabel>Vehicle Batches</relationshipLabel>
    <relationshipName>Vehicle_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Acriss_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>CAZZ</fullName>
    </customValue>
    <customValue>
        <fullName>CDAE</fullName>
    </customValue>
    <customValue>
        <fullName>CDAH</fullName>
    </customValue>
    <customValue>
        <fullName>CDAR</fullName>
    </customValue>
    <customValue>
        <fullName>CDMR</fullName>
    </customValue>
    <customValue>
        <fullName>CFMR</fullName>
    </customValue>
    <customValue>
        <fullName>CLAE</fullName>
    </customValue>
    <customValue>
        <fullName>CLAH</fullName>
    </customValue>
    <customValue>
        <fullName>CLAR</fullName>
    </customValue>
    <customValue>
        <fullName>CWAH</fullName>
    </customValue>
    <customValue>
        <fullName>CWAR</fullName>
    </customValue>
    <customValue>
        <fullName>CWMR</fullName>
    </customValue>
    <customValue>
        <fullName>ECAE</fullName>
    </customValue>
    <customValue>
        <fullName>ECMR</fullName>
    </customValue>
    <customValue>
        <fullName>ETMR</fullName>
    </customValue>
    <customValue>
        <fullName>FDAR</fullName>
    </customValue>
    <customValue>
        <fullName>FFAR</fullName>
    </customValue>
    <customValue>
        <fullName>FVAR</fullName>
    </customValue>
    <customValue>
        <fullName>FWAH</fullName>
    </customValue>
    <customValue>
        <fullName>FWAR</fullName>
    </customValue>
    <customValue>
        <fullName>IDAE</fullName>
    </customValue>
    <customValue>
        <fullName>IDAR</fullName>
    </customValue>
    <customValue>
        <fullName>IFAH</fullName>
    </customValue>
    <customValue>
        <fullName>IFAR</fullName>
    </customValue>
    <customValue>
        <fullName>IFMR</fullName>
    </customValue>
    <customValue>
        <fullName>ILAE</fullName>
    </customValue>
    <customValue>
        <fullName>ILAH</fullName>
    </customValue>
    <description>Acriss Codes used in SIXT DK</description>
    <masterLabel>Acriss Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestUtilitySIXT.cls
/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * Test utility class.
 * Utility methods to create common data structure for testing.
 *
 *
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author         Marek Smerak      <marek.smerak@wipro.com>
 * @modifiedBy     Marek Smerak      <marek.smerak@wipro.com>
 * @version        1.0
 * @created        2022-04-01
 * @modified       2022-04-01
 * @systemLayer    Automatization
 * @see            SIX-4
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @changes
 * v1.0            marek.smerak@wipro.com
 * 2022-04-01      initial version
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┘
 */
@isTest
public with sharing class TestUtilitySIXT {
    public final static String ACCRIS_CODE = 'ECAE';
    public final static String VEHICLE_GROUP_NAME = 'Group Unit Test + ' + ACCRIS_CODE;
    public final static String SERVICE_GROUP_NAME = 'Group Unit SERVICE Test + ' + ACCRIS_CODE;
    public final static String BATCH_DESCRIPTION = 'This is Unit Test 534ui';

    // creates batch together with vehicle group and other required objects
    public static vehicleBatch__c createBatch() {
        // Service and Damage Group
        Service_and_Damage_Group__c sdGroup = createServiceAndDamageSetup(SERVICE_GROUP_NAME);
        // Vehicle Group
        Vehicle_Group__c vGroup = createVehicleGroup(VEHICLE_GROUP_NAME, ACCRIS_CODE, sdGroup.Id);
        // Batch record
        return createBatch(BATCH_DESCRIPTION, vGroup.Id);
    }

    // create batch for specified vehicle group and description
    public static vehicleBatch__c createBatch(String batchDescription, Id vehicleGroupId) {
        // Vehicle batch
        VehicleBatch__c testBatch = new VehicleBatch__c();
        testBatch.Description__c = batchDescription;
        insert testBatch;
        return testBatch;
    }

    // create Service_and_Damage_Group__c and related Service and Damage Costs
    public static Service_and_Damage_Group__c createServiceAndDamageSetup(String groupName) {
        // Service and Damage Group
        Service_and_Damage_Group__c sdGroup = new Service_and_Damage_Group__c();
        sdGroup.Name = groupName;
        insert sdGroup;
        // Service and Damage Costs
        List<ServiceAndDamageCost__c> damageAndServiceMatrix = new List<ServiceAndDamageCost__c>();
        Decimal baseDamage = 1000;
        Decimal baseService = 200;
        for (Integer i = 1; i <= 36; i++) {
            ServiceAndDamageCost__c singleMonth = new ServiceAndDamageCost__c();
            singleMonth.Period_Month__c = i;
            singleMonth.Service_and_Damage_Group__c = sdGroup.Id;
            singleMonth.Damage_Cost__c = baseDamage - (i * 10);
            if (i > 12) {
                singleMonth.Tyres_Service_Cost__c = baseService;
            } else {
                singleMonth.Tyres_Service_Cost__c = 0;
            }
            damageAndServiceMatrix.add(singleMonth);
        }
        insert damageAndServiceMatrix;
        return sdGroup;
    }

    // create a vehicle group with specified accris codes
    public static Vehicle_Group__c createVehicleGroup(String groupName, String codes, Id sdGroupId) {
        Vehicle_Group__c vGroup = new Vehicle_Group__c();
        vGroup.Name = groupName;
        vGroup.Codes__c = codes;
        vGroup.Service_and_Damage_Group__c = sdGroupId;
        insert vGroup;
        return vGroup;
    }

    public static Fleet_Forecast__c createFleetForecast(Id vehicleGroupId, Date firstDay, Date lastDay, Map<String, Object> params) {
        Fleet_Forecast__c ff = new Fleet_Forecast__c();
        ff.Vehicle_Group__c = vehicleGroupId;
        ff.First_Day__c = firstDay;
        ff.Last_Day__c = lastDay;
        for (String fieldName : params.keySet()) {
            ff.put(fieldName, params.get(fieldName));
        }
        // required fields
        ff.Year__c = String.valueOf(firstDay.year());
        Integer theMonth = firstDay.month();
        if (theMonth < 10) {
            ff.Month__c = '0'+theMonth;
        } else {
            ff.Month__c = String.valueOf(theMonth);
        }
        insert ff;
        return ff;
    }

    // tax calculation settings
    public static TaxCalculation__c createTaxCalculationSettings() {
        // custom settings for tax calculation
        TaxCalculation__c taxSetup = new TaxCalculation__c(
            Interest_Rate__c = 2.1,
            Period_1_Length__c = 3,
            Period_1_Rate__c = 2,
            Period_2_Length__c = 33,
            Period_2_Rate__c = 1,
            Last_Period_Rate__c = 0.5
        );
        insert taxSetup;
        return taxSetup;
    }

    // create a vehicle
    public static Vehicle__c createVehicle(Id batchId, Map<String, Object> params) {
        Vehicle__c testVehicle = new Vehicle__c();
        testVehicle.Vehicle_Batch__c = batchId;
        for (String fieldName : params.keySet()) {
            testVehicle.put(fieldName, params.get(fieldName));
        }
        insert testVehicle;
        return testVehicle;
    }
}